### ISSUE TITLE
Improve description of Poisson solver in the documentation.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#102]
> Is the [description](https://climate-machine.github.io/Oceananigans.jl/latest/algorithm/#Discrete-Fourier-spectral-method-1) correct? I thought the solver does not use a Fourier transform --- rather, it uses the Fast Fourier transform *algorithm* to compute the solution to the discrete Poisson equation.
>
> Or am I missing something?
>
> Might be good to add links to the papers that describe this method.
>
> _Originally posted by @glwagner in https://github.com/climate-machine/Oceananigans.jl/issues/100#issuecomment-468945344_

**Comment by glwagner** [comment]
It seems the original reference to this method is

["Fast Fourier transforms for direct solution of poisson's equation with staggered boundary conditions" by Ulrich Schumann and Roland A Sweet (J Comp Phys 1988).](https://www.sciencedirect.com/science/article/pii/0021999188901027)

Note that after equation (1) it is claimed that 'inhomogeneous boundary conditions can be incorporated into `y1`'.

I'm not sure @jm-c @christophernhill --- do we always have Neumann-staggered or "cyclic" (periodic) boundary conditions on pressure?

**Comment by glwagner** [comment]
The algorithm is also described in 

["PoisFFT – A free parallel fast Poisson solver" by V Fuka (Appl Math and Comp 2015).](https://www.sciencedirect.com/science/article/abs/pii/S0096300315003057)

There is also [code corresponding to this paper on github](https://github.com/LadaF/PoisFFT).

The core of the method is an eigenfunction expansion of the discrete Poisson operator... I think?

Perhaps we can call this a `EigenPoissonSolver`, or even `FFTPoissonSolver` --- through we should use caution to avoid misleading people into thinking that our code is spectral. This algorithm solves the Poisson equation when it has been *discretized on a staggered grid*. We should not discuss spectral methods or Fourier transforms, and the word 'spectral' should not appear anywhere in the code. I think this is very misleading. It should be a high priority to change this language.

By the way, it may make sense to put the Poisson solver a separate package. It will be useful to other people, and implementing it as a stand-alone package will allow us to benefit from community development. Is there a reason why we can't do this?

**Comment by ali-ramadhan** [comment]
Thanks for linking to the papers, we consulted them a while back but forgot to reference them in the documentation. Another needed change is that I incorrectly use the term geopotential. 

We can definitely put them in a separate package, I'm sure someone else might find it useful. We might still need to have a separate version for ourselves that integrates with `CellField`s, pre-allocated wavenumbers, and integrates the DCT with the time stepping on the GPU. So might be better if we just spawn off a package as the core functionality of solving the poisson equation can be done in a small amount of code and doesn't need frequent updates.

**Comment by glwagner** [comment]
The pre-calculated wavenumbers should be part of the package. I’m not quite sure where field abstractions come in, so I don’t understand your comment, but I’d note that this solution method is specific to staggered grids. Presumably the external package will eventually have CPU, GPU, and MPI-based solvers.

**Comment by ali-ramadhan** [comment]
Yes it its specific to staggered grids so it's quite specialized but it was annoying figuring out exactly how to do it so definitely worth a package.

**Comment by glwagner** [comment]
I'm going to work on this. I would also like to improve the solver implementation. Why are there [different spectral solvers](https://github.com/climate-machine/Oceananigans.jl/blob/3cd4ae32cb4d716bc6470a6e7ba484ed98d60de7/src/spectral_solvers.jl#L4) for [different devices](https://github.com/climate-machine/Oceananigans.jl/blob/3cd4ae32cb4d716bc6470a6e7ba484ed98d60de7/src/spectral_solvers.jl#L215)? Can we combine them into one type with the `Device` as a type parameter?

**Comment by ali-ramadhan** [comment]
Awesome! The two solvers do pretty different things at this point because
CuFFT doesn't do DCTs or r2r transforms but I've also baked in some
performance optimizations to reduce memory access and operation count. We
should be able to hide some of it away with dispatch but some of the
optimizations are baked into the time stepping so not completely...

Might be easier to talk in person when we meet later today?

**Comment by glwagner** [comment]
There are two issues open on this topic now. Where should we discuss?

Here is my proposed refactor:

https://github.com/glwagner/Oceananigans.jl/blob/poisson-solver-refactor/src/poisson_solver.jl

If we move to a new package, we can improve the documentation there.

The more I think about a separate package the more it makes sense...

**Comment by glwagner** [comment]
@ali-ramadhan do you know how to calculate the permutation vector for the `NeumannFFT` Poisson solver (that we use on the GPU)?

**Comment by glwagner** [comment]
Further documentation is needed to explain the permutation required to compute the DCT using the FFT on a GPU. However, I believe we should make these changes when we move the poisson solver to an independent package. For now, #109 is sufficient.

**Comment by ali-ramadhan** [comment]
@glwagner Sorry for not replying earlier. I don't have any code that computes the permutation vector although I probably have something scribbled in my notebook...

**Comment by glwagner** [comment]
@ali-ramadhan no worries!

I don't think we need code (after all, we have the code in `Oceananigans.jl`) --- I think we just want to express it symbolically for the purposes of the documentation.
