### ISSUE TITLE
Broadcasting over Arrays and CuArrays instead of calling kernels.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#108]
> @ali-ramadhan why not broadcast over CuArrays? Is there a Performance hit?
> 
> _Originally posted by @glwagner in https://github.com/climate-machine/Oceananigans.jl/issues/104#issuecomment-469749450_

**Comment by ali-ramadhan** [comment]
Based on some previous benchmarks I think so
https://github.com/climate-machine/Oceananigans.jl/blob/3cd4ae32cb4d716bc6470a6e7ba484ed98d60de7/benchmark/gpu.jl#L164-L198
Basically I wrote an _x_-difference operator that used `@. @views` which allowed it to act on Arrays and CuArrays, and when acting on a CuArray it was only ~10x faster compared to single-core CPU performance. While the entire time-stepping loop we have using GPUifyLoops.jl is ~90x faster.

**However** I don't think I did the benchmarking there properly (have to use `@benchmark CuArrays.@sync` I believe) and maybe I didn't use `@. @views` properly.

I think using broadcasts would make the code much more readable, but I can think of a few drawbacks (mainly related to performance):

1. I don't know how to fuse kernels when doing broadcasts. E.g. we might be able to do something like
```julia
@. Gu = calc_RHS_u(u, v, w, ...)
@. Gv = calc_RHS_v(u, v, w, ...)
...
```
which would look cleaner but then `update_source_terms!` would end essentially end up in several kernels. From talking with you I believe this shouldn't matter as kernel launches are cheap and the broadcast operator should essentially do exactly what `update_source_terms!` does, but I'm not 100% sure of this and we may lose out on performance.

2. We may want to fine tune our kernel launches, e.g. by using the thread-block layout we want which is probably possible, I'm just not very familiar with the CuArrays.jl package.

3. Some kernels, e.g. ones that do permutations like `calculate_source_term_divergence_gpu!` and `idct_permute!` can't be broadcasted over I think, but these are the exception rather than the rule.

To really find out whether we take a performance hit we might have to refactor the time-stepping to use broadcasting then benchmark the two approaches on CPU, GPU, and multi-GPU architectures (not sure if CuArrays.jl will do multi-GPU arrays yet). This will become much easier once #67 is resolved.

**Comment by glwagner** [comment]
I'm not suggesting we should always use broadcasting. I'm just wondering if it's ok to use it for simple operations. It's a nice abstraction that works on CPUs and GPUs for simple calculations / global array updates ([for example](https://github.com/glwagner/StaggeredPoisson.jl/blob/d104825ba33f184af3b90ca0d958247d0011c7ad/src/solvers.jl#L148)).

**Comment by ali-ramadhan** [comment]
Ah sorry I must have misunderstood your question. Yeah I think broadcasts
tend to perform really well on scalar operations so I don't see why not.

**Comment by vchuravy** [comment]
> Ah sorry I must have misunderstood your question. Yeah I think broadcasts
> tend to perform really well on scalar operations so I don't see why not.

there is sadly a performance difference between `map`, since `broadcast` need to check dimensions
