### ISSUE TITLE
Broadcasting and operations on different Field types

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#12]
Right now I've decided to not implement broadcasting for Field types. It would be really nice but I'd have to figure out how to take into account the different field types, e.g. can broadcast `T .+ S` as they're both of type `CellField` but not `u .+ v` as `u::FaceFieldX, v::FaceFieldY`.

Maybe even take it further and implement `u .+ v` which would have to do `u .+ avgx(avgy(v))`, and isn't commutative anymore.

**Comment by glwagner** [comment]
Maybe we should take a step back and think about what our goal is? What do we want from this system? Will this simplify the MITgcm algorithm?

**Comment by ali-ramadhan** [comment]
I think broadcasting for same-field operators, e.g. `CellField .+ CellField` would be really useful and make the code more readable. The simplification here is fewer loops to look at which is a big plus I think.

But cross-field broadcasting is a bit trickier so might be better to leave it unimplemented especially as it's not a very common operation, I only use it when adding `f .* v` to `Gu` or `f .* u` to `Gv`. Without it you would have to explicitly write `u .+ avgx(avgy(v))` so if you forget it then it might make finding the bug a bit harder. With it, you can just write `u .+ v` with the averaging happening behind the scenes, so you might apply it by mistake without realizing it. Another potentially difficult bug to find.

I feel like everyone has a different opinion on this but in my mind, I'm thinking this would make the code easier to read and write (short-term), and ultimately easier to extend by users (long-term).

I just sometimes use issues leave random TODO notes and ramble.

**Comment by ali-ramadhan** [comment]
Will not implement cross-field operations for now, e.g. `FaceFieldX .+ CellField`. Too complex and rarely used.

**Comment by ali-ramadhan** [comment]
Reopening as this is becoming relevant for online diagnostics which may need a lot of these operations. E.g. `w*T` as @glwagner points out.

**Comment by ali-ramadhan** [comment]
This was resolved in PR #463.
