### ISSUE TITLE
We can reduce memory usage in the Poisson solver by a factor of 2.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#122]
We don't need to store both `f` and `ϕ`. When converting the `f` Fourier coefficients to `ϕ` coefficients, we can just overwrite the `f` array.

This will be great because the Poisson solver requires `Complex{Float64}` so we free up quite a bit of memory.

We can then get rid of `fCC2` in `StepperTemporaryFields`, move `fCC1` somewhere else like `PoissonSolver` or `Model`, and I think we don't need `fC1` anyways. So we get rid of the `StepperTemporaryFields` struct, and end up storing **zero** intermediate calculations!

**Comment by glwagner** [comment]
Also, the 'factors' that are stored as 3D arrays should really be stored as 1D arrays.
