### ISSUE TITLE
Optimal χ in modified Crank-Nicholson Adams-Bashforth time stepping is 1/8.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#125]
@jm-c's favorite value is 1/10. Probably won't make a huge difference.

See: https://epubs.siam.org/doi/abs/10.1137/0732037

**Comment by glwagner** [comment]
Can you ref the place in the code this is defined?

**Comment by ali-ramadhan** [comment]
https://github.com/climate-machine/Oceananigans.jl/blob/3b1518355df2f9bfcb81d702e3d5c55f52ab4757/src/time_steppers.jl#L7

https://github.com/climate-machine/Oceananigans.jl/blob/3b1518355df2f9bfcb81d702e3d5c55f52ab4757/src/time_steppers.jl#L203-L207

Might be good to double check with @jm-c before changing this.

**Comment by ali-ramadhan** [comment]
@jm-c says we're just using AB2 so don't think this is relevant.

**Comment by glwagner** [comment]
In AB2 there is no tunable parameter.

**Comment by ali-ramadhan** [comment]
Yes it's not just AB2 but it's not Crank-Nicholson apparently (which is implicit-explicit).

**Comment by glwagner** [comment]
In the language of the paper, the method we are using sets c = -2gamma to obtain a completely explicit scheme that resembles AB2, but still has a tunable parameter "gamma". The time-stepping method we are using is in the category of those presented in the paper.

**Comment by ali-ramadhan** [comment]
Closed in #128 (which was merged into #118).
