### ISSUE TITLE
Adams-Bashforth time stepping should not be used for first time step.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#127]
Either an explicit forward-Euler step should be taken or we can just set χ to be -0.5 for the first time step.

It shouldn't make a huge difference for what we're doing now.

**Comment by glwagner** [comment]
This should be an extremely high priority to fix.

**Comment by glwagner** [comment]
why doesn't it make a difference? Isn't the time integration incorrect?

**Comment by ali-ramadhan** [comment]
Fixed in #128 

Yes the time integration was incorrect but only at the first time step and the error was small enough that it didn't matter for getting e.g. deep convection to look qualitatively correct.

But it will matter a lot for testing and debugging as you point out.

**Comment by ali-ramadhan** [comment]
Fixed in #118.
