### ISSUE TITLE
Store model metadata as parameterized types in the Model struct.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#133]
This will take a bit of clean up. Should also make the architecture abstract types instead of symbols so they can be dispatched on:
```julia
abstract type Architecture end
struct CPU <: Architecture end
struct GPU <: Architecture end

# Maybe in the future?
struct MultiCPU <: Architecture end
struct MultiGPU <: Architecture end
```

**Comment by glwagner** [comment]
Shouldn’t we use the types defined by GPUifyLoops?

**Comment by ali-ramadhan** [comment]
We dispatch (or will want to dispatch) on `CPU` and `GPU` in many places that aren't GPUifyLoops.jl related. We might also want e.g. `MultiGPU` types that won't be in GPUifyLoops.jl. So I think it's best if we use our own types here.

**Comment by glwagner** [comment]
For the new types, we can add new subtypes of the “Device” abstract type in
GPUifyLoops. Why isn’t this a good design? Seems it would save clutter and
simplify the code since we don’t have to translate between Oceananigans.GPU
and GPUifyLoop.GPU, etc.

**Comment by glwagner** [comment]
These types are just identifiers so there is no practical difference between our own GPU type and GPUifyLoops.GPU. We can easily dispatch on GPUifyLoops.GPU. We can even export it to users as “GPU”.

**Comment by glwagner** [comment]
The code is even literally the same if you just write 

import GPUifyLoops: Device, CPU, GPU

const Architecture = GPUifyLoops.Device

struct MultiCPU <: Architecture end

Etc.

**Comment by ali-ramadhan** [comment]
I understand there's no difference, but I think it's bad practice to rely on another package for such a fundamental data type that will be a main parameter of the core `Model` struct. We're talking about a _few_ lines of "clutter", which it isn't as it's fundamental to what the model does.

What if GPUifyLoops.jl gets deprecated in favor of another package? Or what if the types change later? What if it's abandoned in a year? We're not in control. Even a small change in how GPUifyLoops.jl defines the types will force us do a ton of refactoring.

**Comment by glwagner** [comment]
Well, `GPUifyLoops` is already core to the functionality of `Oceananigans`; also if a new `Device` type is supported by `GPUifyLoops`, it will be automatically supported by `Oceananigans` with no code changes.

But those updates probably won't come rapidly, so the decision isn't really that important either way, I don't think. I'm fine if you want to define new types.

You'll have to use `import` rather than `using GPUifyLoops`, because `CPU` is exported by `GPUifyLoops`.

Will you then write translations functions like 

```julia
dev(::Oceananigans.CUDA) = GPUifyLoops.CUDA
dev(::Oceananigans.CPU) = GPUifyLoops.CPU
```
to use in the kernels?

**Comment by ali-ramadhan** [comment]
I agree that GPUifyLoops.jl is core to functionality but I don't think it's within its scope to extend to distributed architectures. I still think it's bad design to have the GPUifyLoops structures showing up e.g. in the Poisson solvers where it has nothing to do with GPUifying loops.

Yeah I was thinking of using a dictionary to map between the two definitions but the translation functions you proposed is even better.

**Comment by glwagner** [comment]
Okay, I guess I just thought that the GPUifyLoop `Device` and the proposed `Architecture` were conceptually "identical" or nearly so (representing some execution / memory model that needs to be dispatched against), but perhaps I didn't completely understand your proposal.

Not too important anyways.

**Comment by ali-ramadhan** [comment]
@glwagner Do you think the floating point number type, e.g. `Float32` or `Float64` should be a parameter of the `Model` struct?

Feels to me that it should really be a parameter type of the `Grid` and `Field` structs, not the `Model` struct.

**Comment by glwagner** [comment]
I agree --- it only needs to be in one place.

`Grid` might be the right place since you'll need it for `Δx`.

The array types have to be parameters of `Field` so the element type is implicitly part of `Field`, i.e. you could have

```julia
eltype(f::Field{..., A}) where A = eltype(A)
```

It should probably only become a type parameter in the places it is explicitly needed.
