### ISSUE TITLE
Using Reqiures.jl for optional GPU usage

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#14]
Instead of these 3 lines:

https://github.com/ali-ramadhan/Oceananigans.jl/blob/cpu-gpu-shared-kernels/src/Oceananigans.jl#L56

it might be possible to use [Requires.jl](https://github.com/MikeInnes/Requires.jl)

**Comment by ali-ramadhan** [comment]
Didn't know about lazy package loading, thanks for pointing it out!

The model runs on GPUs (albeit pretty slowly right right now) so I'm in the process of cleaning up the code before thinking about optimizing for performance, this should come in handy.

**Comment by glwagner** [comment]
This may be of interest!

https://github.com/glwagner/CuBenchmarks
