### ISSUE TITLE
Turn Oceananigans.jl into a real Julia package.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#142]
I tried submitting it as a package through an attobot request a few weeks ago but the PR build failed on METADATA.jl and I'm not sure why.

Well, I think this was the error but not sure what to do about it as I put Julia 1.1 in the REQUIRE file.
```
ERROR: LoadError: METADATA/Oceananigans/versions/0.4.0/requires: no julia entry (>= 0.6.0 needed)
```

See:
* https://github.com/JuliaLang/METADATA.jl/pull/21774

**Comment by vchuravy** [comment]
It's `julia 1.1` not `Julia 1.1`

**Comment by ali-ramadhan** [comment]
Ah that's a dumb mistake on my part. I'll fix that and try again, thanks!

**Comment by ali-ramadhan** [comment]
Closing as 5.0.1 finally passed CI on METADATA.jl: https://github.com/JuliaLang/METADATA.jl/pull/22656
