### ISSUE TITLE
z boundary conditions are being applied Nz times

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#150]
https://github.com/climate-machine/Oceananigans.jl/blob/608479d50855dd9c285e13953f7c6fac1603156e/src/time_steppers.jl#L377

This kernel should be launched with `blocks=(Bx, By)` otherwise the boundary conditions at the top and bottom are applied `Bz` times (`Bz = Nz` right now).

@SandreOuza and I fixed this on a branch and confirmed that the free convection examples work with this change. It needs to be merged into master ASAP though.

The _x_ and _y_ boundary conditions probably also need a similar change on the lines above.

**Comment by glwagner** [comment]
Should we modify the tests to catch this bug?

**Comment by ali-ramadhan** [comment]
That's definitely a good idea.

I think your tests would have already caught it if we ran the tests on the GPU as well, which I tried to do as part of #140 but sidestepped it meant having to resolve #64 (which is a very easy issue) so we can run GPU models on any grid size.
