### ISSUE TITLE
Change AB-2 parameter to 0.5 + χ to offer first order forward time stepping

### ISSUE THREAD

**Issue by jm-c** [climate-machine/Oceananigans.jl#160]

**Comment by jm-c** [comment]
It would be nice if the quasi-AB-2 epsilon parameter "χ" was a model parameter that can be
easily changed. Right now it looks like it's set to 0.1 at top of time_steppers.jl 
but the value that is used is not this one but is instead hard coded to 0.125

**Comment by glwagner** [comment]
It could make sense to create a struct called, eg, QuasiAdamsBashforthTimestepper that holds all the time-stepper-related fields: G, Gp, chi — what else?

**Comment by ali-ramadhan** [comment]
This has been cleaned up in #147 but I agree it would be nice to store it in a nice struct.

What is the epsilon parameter?

**Comment by jm-c** [comment]
@ali-ramadhan I did not see this in PR #147 (too many lines of diff for time_steppers.jl, so i missed this).
But regarding your question about "epsilon", this is just an other name for parameter "χ" (chi).
In fact, I would prefer to have "0.5 + χ" i beeing called the AB-2 parameter; this way, if set to zero then 
we recover a simple first order forward time stepping.

**Comment by ali-ramadhan** [comment]
Yeah sorry I wasn't expecting anyone to wade through #147, I also butchered the line endings in `time_steppers.jl`...

That might be a nice enhancement where we change the AB-2 parameter to be `0.5 + χ`, then we can have two time stepping schemes.

**Comment by glwagner** [comment]
It is now possible to change this parameter by instantiating a model and then writing

```julia
model.timestepper = AdamsBashforthTimestepper(eltype(model.grid), model.arch, model.grid, -0.5)
```

We can make it a bit easier to change `χ` too --- perhaps by providing an alternate constructor for the `AdamsBashforthTimestepper`?

**Comment by ali-ramadhan** [comment]
Should be fine. I think the timestepper is flexible enough now to modify `χ` which is nice whereas before it was hard-coded in.
