### ISSUE TITLE
Changes that might help with Float32 precision issues

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#161]
@jm-c suggested the following changes that might improve `Float32` precision for simulations with 100,000+ iterations.

> Regarding issue with float32 precision: I looked to the code and
> I can see few things that would be easy to change and could make some difference
> regarding this precision issue:
> 1) Temp in Celcius instead of Kelvin (but this is probably not a big problem)
> 2) recompute W from continuity instead of stepping forward W using: G_w - d.PNH/dz
> 3) apply pressure solver on provisional solution:
>    with RHS = Div(u*,v*,w*) with u* = U + DeltaT * Gu (same for v*,w*)
>  instead of on tendencies with RHS = Div.(Gu,Gv,Gw)
> 
> The problem with the way (2) is currently done is that the error in continuity equation
> are larger ; And with the way we currently do (3), these error can accumulate with time.
> Finally, with T in Kelvin, error in continuity equation can produce larger error in
> temperature.

**Comment by glwagner** [comment]
I think also adjusting dimensions/non-dimensions could help --- for example, changing to `κ=1` and adjusting initial conditions / time-step to produce the identical physical scenario that was produced with `κ=1e=4` and dimensional stuff might be illuminating.
