### ISSUE TITLE
Safely using @inbounds

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#164]
> Another thing I noticed is that `@inbounds` is used in places where it can't really be guaranteed, like *inside* [difference operator functions](https://github.com/climate-machine/Oceananigans.jl/blob/master/src/operators/ops_regular_cartesian_grid.jl). I couldn't figure out how to test this, but I wonder if `@inbounds` propagates to all of the functions that are called inside its scope (is that the right language)? 
> 
> Specifically I'm referring to patterns like the [RHS calculation for u](https://github.com/climate-machine/Oceananigans.jl/blob/2220ee62685a0570d4dec944f148634a539e9220/src/time_steppers.jl#L160), which is `@inbounds`, but subsequently calls operators like [this](https://github.com/climate-machine/Oceananigans.jl/blob/2220ee62685a0570d4dec944f148634a539e9220/src/operators/ops_regular_cartesian_grid.jl#L71) that are *also* have `@inbounds`.
> 
> In other words, we only need *one* `@inbounds` statement; we don't need multiple nested `@inbounds` statements. @vchuravy can you confirm/deny this? 
> 
> A separate issue with `@inbounds` in places where it can't be guaranteed is that if users write functions / analysis tools using those operators, they might screw up and give out-of-bounds indices to functions that have guaranteed `@inbounds` (and in consequence get mysterious segfaults?) It seems the natural place for `@inbounds` is in the scope of a loop.
> 
> _Originally posted by @glwagner in https://github.com/climate-machine/Oceananigans.jl/issues/163#issuecomment-479829199_

**Comment by ali-ramadhan** [comment]
@glwagner I created a new issue using your comment as it wasn't very relevant to the original issue.

I agree that it's not guaranteed to be in bounds by itself. I guess we guarantee it by looping over the correct indices but this isn't the cleanest way.

I think you're right that this belongs at the loop level where we can enclose the loop inside an `@inbounds` block and `@propagate_inbounds` to inlined functions.

I think @peterahrens suggested using `@propagate_inbounds` a while back (#58), and @vchuravy (https://github.com/climate-machine/Oceananigans.jl/issues/13#issuecomment-479851704) just suggested this as well.

Would definitely be good to refactor the code to do this.

Also see: https://docs.julialang.org/en/v1/devdocs/boundscheck/index.html#Propagating-inbounds-1

**Comment by glwagner** [comment]
Ok, it is relevant to the use of the `Field` abstraction though; part of my comment was referring to the fact that we always index into `f.data` rather than `f`.

**Comment by ali-ramadhan** [comment]
Ah I see, sorry for misunderstanding. I guess I saw three separate issues:
1. Having to always use `f.data` instead of `f` (#13).
2. Safely propagating `@inbounds` (#58 and #164).
3. GPU-compatible `Field` abstractions (#163).

Perhaps all three could be addressed in a single PR.

**Comment by glwagner** [comment]
Found this in the docs:

https://docs.julialang.org/en/latest/devdocs/boundscheck/#Propagating-inbounds-1

I think we want to use this notation for our kernel functions, rather than forcing `@inbounds`.

**Comment by vchuravy** [comment]
Also see https://github.com/JuliaArrays/StaticArrays.jl/pull/564#issuecomment-445499712

**Comment by glwagner** [comment]
We want *both* `@inline` and `@propagate_inbounds` on our kernels --- right?

**Comment by vchuravy** [comment]
`@propagate_inbounds` implies `@inline` and GPUifyLoops will force inline everything

**Comment by ali-ramadhan** [comment]
Don't think this is an issue anymore, thanks @vchuravy!
