### ISSUE TITLE
Casting CuArrays to Arrays for many operations.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#171]
For many purposes, e.g. writing output, calculating statistical diagnostics, etc. that is very inefficient on CuArrays because of scalar operations, it turns out to be faster to just convert the CuArray to an Array and do the operation.

I wonder if there's a nicer way of doing this. I guess CUDAnative.jl has a rough list of CuArray-compatible functions that we should refer to more often.

We can also just use a wrapper function but this feels a little weird and we'd have to remember where we need to use it
```julia
wrapper(A::Array) = A
wrapper(A::CuArray) = Array(A)
```
which isn't much better than always using `Array(A)` as we mostly run on the GPU.

This feels like a pretty minor issue but thought I'd document it here since I found myself doing this several times today.

**Comment by vchuravy** [comment]
so one way to do this is to say `adapt(Array, A)` which then requires no knowledge where A was an Array or a CuArray or a complicated model.

**Comment by ali-ramadhan** [comment]
Don't think this is an issue anymore. At least, it's all handled in the backend.
