### ISSUE TITLE
3D ppn Laplacian operator should be using δ operators.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#18]
To reuse δ! and avg! operators.

**Comment by glwagner** [comment]
This seems out of date. Time to close it?

**Comment by ali-ramadhan** [comment]
Ah it's actually still an open issue but for a different reason so I updated the original post. Doesn't need to be in v0.5 though as it's not used in the time stepping (only testing and diagnostics).
