### ISSUE TITLE
Running with Float32 is slower than Float64 on CPUs

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#188]
Looking at performance benchmarks, Float32 is slower than Float64 on the CPU.

I suspect something is being done wrong somewhere maybe. I have a few ideas:
1. Those benchmarks were run on Google Cloud where the virtual CPUs aren't very performant so I thought it was maybe just a low-end 64-bit CPU where Float32 operations were emulated via Float64 operations resulting in fewer FLOPS. However, even on my own laptop I found Float32 on a CPU to be a bit slower, but just by 5-10% whereas on Google Cloud it was like 30%+ slower.
2. It's likely that Float32 is still being mixed with Float64, and maybe this slows the code down due to too many implicit conversions? (Somewhat related to #34).
3. Unlikely but I wonder if this is a Julia issue... I could perhaps run some simple C code to see if it's a hardware thing or just a weird Julia thing.
4. I thought it looked fine on the GPU as you do see a "speedup" of 10-15% which I took to mean that we were memory bandwidth/latency limited (which is probably true). The V100 GPUs have twice as many FP32 units as they do FP64 units and if FP32 operations are faster, then I expect more than just a 10-15% speedup. So maybe we have similar issues on the GPU, which are preventing us from doing better than 15% speedup. Or maybe the GPU doesn't do implicit conversions and we are actually just memory bandwidth/latency limited.

@glwagner has also pointed out these posts:
* Check out these benchmarks for arithmetic cpu operations: http://nicolas.limare.net/pro/notes/2014/12/12_arit_speed/ Conclusion: _usually_ single precision is faster, but is _occasionally_ comparable or slower depending on the processor (check results for x86-64 Intel Ivy Bridge).
* https://stackoverflow.com/questions/3426165/is-using-double-faster-than-float

**Comment by vchuravy** [comment]
One thing worth checking if that you don't have implict conversion to Float64 somewhere due to Float64 contansts.

**Comment by glwagner** [comment]
There do appear to be implicit conversions occurring in the averaging operators.

**Comment by glwagner** [comment]
This issue may be solved by leveraging the `eltype` of `RegularCartesianGrid` to convert `0.5` to the appropriate type in the averaging operators.

**Comment by glwagner** [comment]
This might be resolved... 😏

**Comment by ali-ramadhan** [comment]
Kind of. We might have a bit more work to do to fix all the float conversions but we know what the problem is so yes I'll close this.
