### ISSUE TITLE
Adaptive time stepping

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#189]
Might be interesting to give adaptive time-stepping a try. @christophernhill says it didn't work super well last time they tried it in the MITgcm but that might have been a long time ago. I suspect for most MITgcm runs, which act on large horizontal domains, the time step is severely limited by vertical motions which may not be true for all Oceananigans simulations. Not sure if this changes anything.

I suspect you just calculate the time step using
```julia
C = 1  # Maximum Courant number. Probably 1 for our explicit AB2 time-stepping scheme.

Δt_x = C*Δx / maximum(abs.(u))
Δt_y = C*Δy / maximum(abs.(v))
Δt_z = C*Δz / maximum(abs.(w))

Δt = min(Δt_x, Δt_y, Δt_z)
```

Even if we don't use adaptive time-stepping, it might be a useful `CFLChecker` diagnostic that prints warnings when CFL is being violated.

**Comment by glwagner** [comment]
Hmm. Does this mean that MITgcm simulations regularly violate the CFL criterion? 

Follow up q: does MITgcm treats vertical derivatives (including in advective terms) implicitly? That's the only way I can make sense of a situation in which the CFL is regularly violated but the solution remains stable.
