### ISSUE TITLE
To support multiple precision, abstractions like Clock should let the float type be a parameter (like Grid).

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#19]
Shouldn't be mixing precisions.

**Comment by glwagner** [comment]
Can you provide a reference to the code where this is implemented?

**Comment by ali-ramadhan** [comment]
The issue is pretty general but here's an example
https://github.com/ali-ramadhan/Oceananigans.jl/blob/6ec7cc23393bd5fdce846e1b3eb601fcd1901af4/src/clock.jl#L1-L5

`Clock` should be `Clock{T} where T <: Number` then `time` and `Δt` should be of type `T`. This isn't the only struct that needs to be refactored in this way.

**Comment by ali-ramadhan** [comment]
This has been largely fixed by converting as many of our structs to `isbits` structs. The `Clock` struct in particular will never be `isbits` in its current form as it's `mutable`.

**Comment by glwagner** [comment]
Interesting that `mutable`s can't be `isbits`. But `Array` is mutable and `isbits`? Maybe some exceptions...

I do think you should avoid fields with abstract or unspecified types in all cases (when simple, like this one) though, even if just for style points, but also to avoid an unexpected performance gotcha. `Clock{T}` seems appropriate.

**Comment by ali-ramadhan** [comment]
Actually `Array` and `CuArray` aren't `isbits`. But from what I understand, I think CUDAnative uses Adapt.jl to convert a `CuArray` to something like a `CuDeviceArray` which is `isbits` when passing arguments to CUDA kernels, which is what we would have to do to convert our `Field` structs to be `isbits`.

But yeah, definitely agree about avoiding abstract and unspecified types. Comes with learning Julia I guess.
