### ISSUE TITLE
Revise physical constants

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#190]
@jm-c has pointed out that certain constants may not have the correct value for saltwater. Would be good to get this stuff right.

Two points I recall:
* It seems we have both linear and volumetric expansion coefficients? We should probably only be using one?
```julia
βT = 1.67e-4  # First thermal expansion coefficient [1/K]
αᵥ = 2.07e-4  # Volumetric coefficient of thermal expansion for water [K⁻¹].
```
* Only used in scripts/examples but this value may be off for saltwater:
```julia
cₚ = 4181.3  # Specific heat capacity of seawater at constant pressure [J/(kg·K)]
```

**Comment by ali-ramadhan** [comment]
As part of this we should probably cite where we're getting the physical constants from.

**Comment by glwagner** [comment]
@jm-c can you help with this?

**Comment by jm-c** [comment]
C_p = 3991.86795711963 J/kg/K is the reference value of
specific heat capacity (Graham and McDougall, 2013)
