### ISSUE TITLE
Idealized nonlinear equation of state

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#191]
In addition to a linear equation of state (which still need to be improved, see #20) we may want an idealized nonlinear equation of state for simulating e.g. Europa or Enceladus (#143) where a linear equation can't capture all the dynamics and a super-realistic Earth-specific TEOS-10 equation of state may not be valid.

I think a common suggestion has been the idealized equation of state proposed by [Roquet et al. (2015)](https://journals.ametsoc.org/doi/full/10.1175/JPO-D-15-0080.1). See their equations (17) and (18).

**Comment by johncmarshall54** [comment]
Yes, roquet would be good to code up. John
