### ISSUE TITLE
Warning/error if Julia version is too low

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#193]
As GPUifyLoops.jl relies on Julia 1.1+, so does Oceananigans. We should print an error (there must be some Julia pattern people do here) if someone tries to run Oceananigans with Julia <1.1.

Currently it's really bad for usability as Ubuntu repositories are ancient as usual and still on Julia 1.0.3, and Debian is probably even worse. And you get pretty cryptic messages if running Oceananigans from Julia 1.0.

**Comment by vchuravy** [comment]
https://github.com/vchuravy/GPUifyLoops.jl/blob/951ddadfecb47b5636129d45467316aa185b32e3/src/GPUifyLoops.jl#L3-L5

**Comment by ali-ramadhan** [comment]
Thanks, that was easy!
