### ISSUE TITLE
Dynamically install packages like Plots.jl and ArgParse.jl for examples.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#195]
I don't think we should depend on a heavy package like Plots.jl, but we might want to automatically install and load it when someone runs an example like the rising thermal bubble one on the README.

Might be related to #14 so Requires.jl would help but we also want to add/build the package too.

**Comment by vchuravy** [comment]
I think the right strategy is to have a separate Julia Project.toml for the example that is using Plots etc.

**Comment by ali-ramadhan** [comment]
Ah yeah that would be cleaner. I think we can then dynamically switch between different Project.toml files via `Pkg.activate()` and users won't have to juggle different environments.

**Comment by glwagner** [comment]
Maybe one shared environment for examples? We may have enough examples eventually to categorize them, ie, `cpu_examples`, `gpu_examples`, `fancy_visualization_examples`, `fancy_data_generation_examples`

**Comment by ali-ramadhan** [comment]
Yeah I think we definitely want `cpu` and `gpu`, then `examples` would be a good third one for now. Plots.jl would be the big dependency.

**Comment by ali-ramadhan** [comment]
I think this pattern takes care of this issue:
https://github.com/climate-machine/Oceananigans.jl/blob/7a4142c43b6cf1f5541687fa349d75cb52605c50/examples/deepening_mixed_layer.jl#L3-L10

I think the problem with multiple `Project.toml` files is that it's awkward for users just adding the package via `]add Oceananigans` to switch between different environments just to run a simple example. But an error like `module PyPlot not found` is clear enough that they just need `PyPlot` to run the example.
