### ISSUE TITLE
GPU Poisson solver tests

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#200]
Kind of scary that we don't have tests for this. I wrote some as part of PR #167 but commented them out as I couldn't get them to work (I kept getting some CUDA error). I should make sure to finish that off.

**Comment by glwagner** [comment]
This was solved, correct?

**Comment by ali-ramadhan** [comment]
Haven't looked at them since I opened this issue but I know CUDA error reporting has improved so worth looking at again.
