### ISSUE TITLE
Development milestones and order?

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#207]
Not supposed to be concrete but just to lay out some goals for big new features and prioritize them based on our needs. Also in case I forgot about them.

Most of these can be done independently so the version ordering is mostly for priority.

* v0.6: Arbitrary LES closures (Smagorinsky and AMD implemented)
* v0.7: Halo regions (PR #167)
* v0.8: Reduce memory usage by storing fewer fields.
* v0.9: Machine precision mass conservation
* v0.10: channel and boxed/cubed models, i.e. multiple wall-bounded dimensions (PR #180)
* v0.11: True finite volume operators
* v0.12: Variable Δz grid
* v0.13: Higher-order advection schemes (4th order, 3rd order DST, WENO?, Prather??)
* v0.14: GPU performance optimization (GPU hackathon)
* v0.15: Multi-GPU (and multi-CPU?) distributed parallelism (GPU hackathon)
* v0.16: Fuller high-level and API documentation
* v0.17: Fast on-the-fly diagnostics framework (CPU and GPU friendly)
* v1.0: Awesome LES model!
* v1.1: Hydrostatic mode
* v1.2: Spherical grid (pole problem)?
* v1.3: Cubed sphere grid?
* ...

**Comment by vchuravy** [comment]
I would recommend using Milestones instead of a big meta issue.

**Comment by ali-ramadhan** [comment]
Ah yes good point. We're kind of already using milestones (only up to v0.7 right now) but this was kind of to discuss which milestones to tackle and in which order. I made the title a bit clearer.

**Comment by johncmarshall54** [comment]
LES closure is a very high priority.

**Comment by ali-ramadhan** [comment]
I've bumped LES closures to v0.6 then so it'll be the next feature we implement.

**Comment by glwagner** [comment]
+1 for LES!

We may want to look into [WENO finite difference stencils](https://www.sciencedirect.com/science/article/pii/S002199910096443X). This can be thought of as another LES scheme, and may also be useful for larger-scale simulations in which ordinary LES closures are suspect.

Getting Float32 to work could perhaps be a lower priority.

I'm not sure what the status of the code comparisons are, but we may want to figure out how to do a c comparison with other LES codes when an LES model is implemented.

**Comment by ali-ramadhan** [comment]
Ah interesting, I thought WENO was a higher-order advection scheme.

I renamed "More conservative time-stepping for Float32" to "Machine precision mass conservation" as it's an issue with Float64 as well but probably does not matter for simulations with fewer than 1~10 million time steps. Might matter for the mixed layer seasonal cycle simulations which go for more than 10 million time steps.

**Comment by glwagner** [comment]
I believe you are correct that WENO is a family of higher order advection schemes — that permit accurate, relatively non-dissipation simulations without explicitly modeled dissipation terms. Maybe the milestone could be broadened to “high-order advection schemes”.

Mass conservation is definitely important.

**Comment by ali-ramadhan** [comment]
Ah I see, would be interesting to see if it does better than an LES closure seeing as AMD can get computationally expensive (but maybe not too expensive if efficiently implemented on a GPU).

I added a "Higher-order advection schemes" milestone which we can prioritize as necessary. I'm sure which advection schemes to use/implement will be a hot topic but for now I'm thinking these might be interesting:
* Centered 4th-order: good to have a formal higher-order scheme. May require bi-harmonic diffusion to be used effectively. We already have an implementation for tracers (#76).
* 3rd order DST:  We have a partial implementation. (#183)
* WENO? Sounds interesting/useful for LES.
* Prather?? Apparently very good and a favorite around here but requires intermediate storage and is DG in spirit, so not sure if we'll use it, especially if we move towards DG anyways.

**Comment by ali-ramadhan** [comment]
Closing as this issue has served its purpose (for me at least). Development milestones are clearer now. Further discussion should occur in more focused issues.
