### ISSUE TITLE
Generic vertical integral operator.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#21]
Should convert `∫δρgdz!(g::Grid, c::PlanetaryConstants, δρ::CellField, δρz::FaceFieldZ, pHY′::CellField)` to a generic vertical integral operator. Is this one particularly special?

**Comment by ali-ramadhan** [comment]
Might be a little difficult. For now we'll stick to the one thread per vertical column from PR #171.

We only have one vertical integral for now anyways.

**Comment by glwagner** [comment]
Huh. Is this a necessary part of the pressure solver? Or is it just included to make transitioning to a hydrostatic solver easier?

**Comment by ali-ramadhan** [comment]
It's part of the `buoyancy_update!` kernel where we calculate the hydrostatic pressure anomaly as the vertical integral of δρ.
