### ISSUE TITLE
Equations in documentation are not dimensionally consistent

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#222]
First confusion:

Equation (1) contains the gradient of kinematic pressure, while equation (7) is written in terms of the dynamic pressure:

https://climate-machine.github.io/Oceananigans.jl/latest/algorithm/

But then, equation (12) adds the two pressures together as if they have the same units. 

Second confusion:

Equation (13) implies that the hydrostatic pressure is a kinematic pressure. 

Yet its calculation [in the code](https://github.com/climate-machine/Oceananigans.jl/blob/7e29af402d6535a25f649520350efcaca7c417d6/src/time_steppers.jl#L130) (see also [here](https://github.com/climate-machine/Oceananigans.jl/blob/master/src/equation_of_state.jl)) suggests that it is defined as a dynamic pressure in the code.

which is it?

Note that the value of rho0 should not affect dynamics in the code.

**Comment by glwagner** [comment]
Found it: the 'buoyancy' is multiplied by rho0 [here](https://github.com/climate-machine/Oceananigans.jl/blob/7e29af402d6535a25f649520350efcaca7c417d6/src/equation_of_state.jl#L36) and then rho0 is divided away [here](https://github.com/climate-machine/Oceananigans.jl/blob/7e29af402d6535a25f649520350efcaca7c417d6/src/time_steppers.jl#L153) and [here](https://github.com/climate-machine/Oceananigans.jl/blob/7e29af402d6535a25f649520350efcaca7c417d6/src/time_steppers.jl#L160).

If we want to continue multiplying and dividing by rho0 in the code, we should update the documentation accordingly (or vice versa --- which I would prefer).

**Comment by ali-ramadhan** [comment]
We decided to go with kinematic pressure \phi.

**Comment by johncmarshall54** [comment]
Rho factors were a big reason why bugs were difficult to track down as
oceananigans was built!

**Comment by glwagner** [comment]
@johncmarshall54 I think you might've meant as *MITgcm* was built. Here *we* are, building (attempting to build) Oceananigans!
