### ISSUE TITLE
Reference or explanation of DCT-FFT translation used for GPU Poisson solver method

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#240]
I cannot find an explanation of the method used to solve Poisson's equation on the GPU either in the documentation or in the source for `Oceananigans`.

Studying both the source code and the FFTW documentation:

http://www.fftw.org/fftw3_doc/1d-Real_002deven-DFTs-_0028DCTs_0029.html

was not sufficient for me to deduce the theory behind the method used.

I can think of two solutions --- "shifting inversion eigenvalues and zeroing the complex part of the FFT", or "reflecting the data about z=0", but the algorithm currently used doesn't appear to fall into either of this categories, unless I am mistaken.

*Note*: there also is no explanation of the method used for the CPU in the documentation or the code. However, studying the code reveals that the cosine transform type is `REDFT10` and the inverse type is `REDFT01`, corresponding to a type-II DCT. Presumably this method uses the "Neumann-Staggered, Neumann-Staggered" eigenfunctions and eigenvalues from [Schumann and Sweet](https://www.sciencedirect.com/science/article/pii/0021999188901027) equation (12)... ?

**Comment by ali-ramadhan** [comment]
You're correct about the CPU method. We also opened an earlier issue to discuss this: #102 

Regarding what the GPU does differently: as cuFFT does not have a DCT function, we have to compute the type-II DCT using the FFT (and the type-III DCT using the IFFT).

The relevant reference for how to do this efficiently (i.e. no padding or extra memory usage required) is:

Makhoul, [_A fast cosine transform in one and two dimensions_](https://ieeexplore.ieee.org/document/1163351?arnumber=1163351&tag=1), IEEE Transactions on Acoustics, Speech, and Signal Processing 28(1) (1980)

but this DSP StackExchange post is probably more useful: https://dsp.stackexchange.com/questions/2807/fast-cosine-transform-via-fft

**Comment by glwagner** [comment]
Ok, thank you. That papers certainly clears up how to go from the n-point FFT to the DCT. To be specific, the permutation and forward 'factors' that are used for the GPU solver are defined in equation (16) and via `W^k_{4N}` in equation (4) and (19a)... ?

As for #102, I simply do not understand at first glance how to get from the eigentransform formulas in Schumann and Sweet (which involve `sine` and `cosine`) to the FFT (which involves a complex exponential). Am I missing something obvious? I feel that some non-trivial algebra is committed from every reference I have seen on this topic. The PoisFFT paper also makes the claim that this is possible but does not offer any justification or clarification.

**Comment by ali-ramadhan** [comment]
> To be specific, the permutation and forward 'factors' that are used for the GPU solver are defined in equation (16) and via W^k_{4N} in equation (4) and (19a)... ?

I had some difficulty figuring out exactly what to do from that paper so I ended up using the factors from these notes (which ended up working):
http://fourier.eng.hmc.edu/e161/lectures/dct/node2.html

> As for #102, I simply do not understand at first glance how to get from the eigentransform formulas in Schumann and Sweet (which involve sine and cosine) to the FFT (which involves a complex exponential). Am I missing something obvious? I feel that some non-trivial algebra is committed from every reference I have seen on this topic. The PoisFFT paper also makes the claim that this is possible but does not offer any justification or clarification.

Yeah this stuff took us a while to figure out at the start. Not sure if I fully understand what you're referring to but I have _tedious_ derivations of Schumann & Sweet's equations (28) and (33) in my notebook that start from the FFTW definitions of the DFT and DCT.

**Comment by glwagner** [comment]
Good to know there are notes somewhere!

The fact that it can't be reproduced from the literature easily suggests that having independent documentation is imperative.

One idea for the future is to 'take notes in the documentation', ie, write the documentation simultaneously with writing out the algorithm (carefully and slowly).
