### ISSUE TITLE
Types of kernel arguments do not seem to be inferred

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#251]
Using `Cthulhu` by running the commands

```julia
using Oceananigans, Cthulhu

model = Model(N=(32, 32, 32), L=(1, 1, 1)) 

@descend time_step!(model, 1, 1)
```

and descending into the call to `store_previous_source_terms!` (I did this using the optimize flag and scrolling to invocation `%206`, then using the warn_type flag), reveals (I think) that for some reason julia cannot infer the types of arguments into any of the kernels. For example, the `Cthulhu` output from that exercise yields

```
@ /Users/gregorywagner/Projects/Oceananigans.jl/src/time_steppers.jl:122 within `store_previous_source_terms!'
15 ┄ %74  = (GPUifyLoops.isdevice)()::Core.Compiler.Const(false, false)
│    %75  = !%74::Core.Compiler.Const(true, true)
│           %75
│    %77  = (Base.getproperty)(grid, :Nx)::Any
```

The type of `grid` is not inferred, and neither is the type of `grid.Nx`. None of the types of the arguments are inferred.

I can fix this problem by explicitly typing all of the arguments except for the floating point type. However, I cannot fix the problem even if I specify that most of the arguments are `AbstractArray`.

Is this causing performance problems? Is this the source of memory allocation during time-stepping?

@vchuravy @ali-ramadhan

**Comment by glwagner** [comment]
This problem could have to do with a failure to infer the types of the forcing functions `F.u, F.v`, etc.

**Comment by vchuravy** [comment]
Many of the model fields are not concretely typed, so Cthulhu has issues with that. PR incoming

**Comment by glwagner** [comment]
We've got a concrete `Model` now.
