### ISSUE TITLE
CPU example in README.md fails

### ISSUE THREAD

**Issue by suyashbire1** [climate-machine/Oceananigans.jl#267]
The line `model.tracers.T.data .= 282.99 .+ 2 .* reshape(hot_bubble_perturbation, (Nx, Ny, Nz))` in the README should be replaced with `data(model.tracers.T) .= model.eos.T₀ .- 0.01 .+ 2 .* reshape(hot_bubble_perturbation, (Nx, Ny, Nz))`.

The former gives a broadcast error. The latter is used in the `rising_thermal_bubble_2d.jl` example and seems to produce the expected bubble.

**Comment by ali-ramadhan** [comment]
Hey Suyesh, thanks for pointing this out!

I literally opened PR #266 which fixed this on the exact same minute that you opened this issue haha.
