### ISSUE TITLE
Halo regions filling functions are not general

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#307]
The `fill_halo_regions!` functions should dispatch on 

1. The location of the field for which halos are being filled (because this determines the values that must be filled), and

2. The type of the boundary condition.

At the moment, it appears that [`fill_halo_regions!`](https://github.com/climate-machine/Oceananigans.jl/blob/8fdff750ee67d41ba3e485819105e3549e774d8a/src/halo_regions.jl#L13) functions dispatch on the *name* of the field (which implies some boundary condition + `Field` type combination)?

**Comment by ali-ramadhan** [comment]
Yeah it wasn't meant to be a permanent solution, dispatching on the boundary condition would be a huge step up. We can then get rid of the hacky dispatching on the name. Thankfully the halo region filling is isolated so it can be easily modified.

**Comment by glwagner** [comment]
This was resolved by #329.
