### ISSUE TITLE
How to impose custom boundary conditions?

### ISSUE THREAD

**Issue by beta-effect** [climate-machine/Oceananigans.jl#314]
I am trying to use the latest version of Oceananigans (`] add https://github.com/climate-machine/Oceananigans.jl.git`).

Is there a new boundary condition API? I had a working simulation which is failing now.

This was working a few days ago.
```
# Set up the model and use an artificially high viscosity ν and diffusivity κ.
model = Model(N=(Nx, Ny, Nz), L=(Lx, Ly, Lz), arch=GPU(),
              ν=1e-4, κ=1e-4)

# Get location of the cell centers in x, y, z and reshape them to easily
# broadcast over them when calculating hot_bubble_perturbation.
xC, yC, zC = model.grid.xC, model.grid.yC, model.grid.zC
xC, yC, zC = reshape(xC, (Nx, 1, 1)), reshape(yC, (1, Ny, 1)), reshape(zC, (1, 1, Nz))

# Set heating flux at the bottom.
Q = 9200  # W/m^2
Rp = 50   # plume radius [m]

r = @. sqrt((xC - Lx/2)^2 + (yC - Ly/2)^2)

bottom_flux = zeros(Nx, Ny, 1)
bottom_flux[r .< Rp] .= g * ɑ * Q / (ρ₀ * cₚ)
bottom_flux =  CuArray(bottom_flux)

model.boundary_conditions.T.z.right = BoundaryCondition(Flux, bottom_flux)
```

This now fails with:
```
ERROR: LoadError: TypeError: in setfield!, expected BoundaryCondition{Flux,Int64}, got BoundaryCondition{Flux,CuArray{Float64,3}}
Stacktrace:
 [1] setbc!(::CoordinateBoundaryConditions{BoundaryCondition{Flux,Int64},BoundaryCondition{Flux,Int64}}, ::Val{:right}, ::BoundaryCondition{Flux,CuArray{Float64,3}}) at /home/betaeffect/.julia/packages/Oceananigans/wiEvh/src/boundary_conditions.jl:81
 [2] setproperty!(::CoordinateBoundaryConditions{BoundaryCondition{Flux,Int64},BoundaryCondition{Flux,Int64}}, ::Symbol, ::BoundaryCondition{Flux,CuArray{Float64,3}}) at /home/betaeffect/.julia/packages/Oceananigans/wiEvh/src/boundary_conditions.jl:80
 [3] top-level scope at none:0
 [4] include at ./boot.jl:326 [inlined]
 [5] include_relative(::Module, ::String) at ./loading.jl:1038
 [6] include(::Module, ::String) at ./sysimg.jl:29
 [7] include(::String) at ./client.jl:403
 [8] top-level scope at none:0
in expression starting at /home/betaeffect/oceananigans/hydrothermal_plume/nukappa1em4/plume.jl:37
```

I am not fully proficient in Julia yet, so wasn't able to figure out from the code how to fix this issue. Is there a simple fix?

**Comment by ali-ramadhan** [comment]
Hey @beta-effect!

Yes as of PR #282 (included in master, but not in v0.8.0), boundary conditions must be specified at `Model` creation time. This is part of an ongoing attempt at making the types we use in Oceananigans more concrete. If we use structs whose types are set once the struct is created (concrete types), then the compile can more easily optimize things as it knows the data type won't change.

The default boundary conditions are given by `ModelBoundaryConditions()` where
```julia
function ModelBoundaryConditions(;
    u = DoublyPeriodicBCs(),
    v = DoublyPeriodicBCs(),
    w = DoublyPeriodicBCs(),
    T = DoublyPeriodicBCs(),
    S = DoublyPeriodicBCs()
   )
    return ModelBoundaryConditions(u, v, w, T, S)
end
```
so I think what you want instead is something like
```julia
T_bc = FieldBoundaryConditions(
    x = CoordinateBoundaryConditions(
        BoundaryCondition(Periodic, nothing),
        BoundaryCondition(Periodic, nothing)),
    y = CoordinateBoundaryConditions(
        BoundaryCondition(Periodic, nothing),
        BoundaryCondition(Periodic, nothing)),
    z = CoordinateBoundaryConditions(
        BoundaryCondition(Flux, 0),
        BoundaryCondition(Flux, bottom_flux)))

bcs = ModelBoundaryConditions(
    u = DoublyPeriodicBCs(),
    v = DoublyPeriodicBCs(),
    w = DoublyPeriodicBCs(),
    T = T_bc,
    S = DoublyPeriodicBCs())
```

We still need to figure the API a little because this gets a little annoying: you need to compute `bottom_flux` before constructing the `Model` but it's nice to use `xC, yC, zC` to compute `bottom_flux` but we get them from `model.grid`...

The easiest thing to do right now might be to just create the model again but with the new `bcs`:
```julia
# Set up the model and use an artificially high viscosity ν and diffusivity κ.
model = Model(N=(Nx, Ny, Nz), L=(Lx, Ly, Lz), arch=GPU(),
              ν=1e-4, κ=1e-4)

# Get location of the cell centers in x, y, z and reshape them to easily
# broadcast over them when calculating hot_bubble_perturbation.
xC, yC, zC = model.grid.xC, model.grid.yC, model.grid.zC
xC, yC, zC = reshape(xC, (Nx, 1, 1)), reshape(yC, (1, Ny, 1)), reshape(zC, (1, 1, Nz))

# Set heating flux at the bottom.
Q = 9200  # W/m^2
Rp = 50   # plume radius [m]

r = @. sqrt((xC - Lx/2)^2 + (yC - Ly/2)^2)

bottom_flux = zeros(Nx, Ny, 1)
bottom_flux[r .< Rp] .= g * ɑ * Q / (ρ₀ * cₚ)
bottom_flux =  CuArray(bottom_flux)

T_bc = FieldBoundaryConditions(
    x = CoordinateBoundaryConditions(
        BoundaryCondition(Periodic, nothing),
        BoundaryCondition(Periodic, nothing)),
    y = CoordinateBoundaryConditions(
        BoundaryCondition(Periodic, nothing),
        BoundaryCondition(Periodic, nothing)),
    z = CoordinateBoundaryConditions(
        BoundaryCondition(Flux, 0),
        BoundaryCondition(Flux, bottom_flux)))

bcs = ModelBoundaryConditions(
    u = DoublyPeriodicBCs(),
    v = DoublyPeriodicBCs(),
    w = DoublyPeriodicBCs(),
    T = T_bc,
    S = DoublyPeriodicBCs())

model = Model(N=(Nx, Ny, Nz), L=(Lx, Ly, Lz), arch=GPU(),
              ν=1e-4, κ=1e-4, bcs=bcs)
```

At least that was my attempt which should work. The API does need some cleaning up and user-friendly love, and @glwagner may have a better solution.

Let me know if this doesn't work!

**Comment by glwagner** [comment]
@beta-effect a more concise solution than provided by @ali-ramadhan is to use

```julia
# Your code here

# Create boundary conditions
Tbcs = FieldBoundaryConditions(z=ZBoundaryConditions(
    top    = BoundaryCondition(Flux, Fθ),
    bottom = BoundaryCondition(Flux, bottom_flux) ))

# Set up the model and use an artificially high viscosity ν and diffusivity κ.
model = Model(N=(Nx, Ny, Nz), L=(Lx, Ly, Lz), arch=GPU(),
              bcs = BoundaryConditions(T=Tbcs),
              ν=1e-4, κ=1e-4)
```

Comments about the API are welcome. The key point here is that the type of the boundary condition must be declared when the model is created.

We should also have an LES model soon, which will preclude the need to use artificially high Laplacian viscosities and diffusivities.

**Comment by glwagner** [comment]
@ali-ramadhan note that a lot of your code is dedicated to setting up the default boundary conditions that are provided in the `BoundaryConditions` constructor, and is therefore not necessary.

**Comment by glwagner** [comment]
@ali-ramadhan @beta-effect something that could make the API slightly more concise is to provide a way to directly set the `z` boundary conditions of a field. Perhaps something like 


```julia
Tbcs = HorizontallyPeriodicBoundaryConditions(
    bottom = BoundaryCondition(Flux, bottom_flux)
)
```

what do you think about that?

**Comment by glwagner** [comment]
See #315. I've implemented constructors for `HorizontallyPeriodicBCs` and `ChannelBCs`.

**Comment by ali-ramadhan** [comment]
That looks much cleaner!

**Comment by beta-effect** [comment]
Thank you @ali-ramadhan and @glwagner for the solutions. They worked!

However, calling `Model` twice was more memory intensive. I ran into out of memory error. Is the first instance not overwritten when the second instance is defined?

Since I have a uniform grid, I was able to manually define `xC`, `yC`, and `zC` and avoid the out of memory error. 

```julia
# Get location of the cell centers in x, y, z and reshape them to easily
# broadcast over them
xF, yF, zF = collect(0:Lx/Nx:Lx), collect(0:Ly/Ny:Ly), collect(0:Lz/Nz:Lz)
xC, yC, zC = 0.5.*(xF[2:end] .+ xF[1:end-1]), 0.5.*(yF[2:end] .+ yF[1:end-1]), 0.5.*(zF[2:end] .+ zF[1:end-1])
xC, yC, zC = reshape(xC, (Nx, 1, 1)), reshape(yC, (1, Ny, 1)), reshape(zC, (1, 1, Nz))

# Set heating flux at the bottom.
Q = 9200  # W/m^2
Rp = 50   # plume radius [m]
r = @. sqrt((xC - Lx/2)^2 + (yC - Ly/2)^2)
bottom_flux = zeros(Nx, Ny, 1)
bottom_flux[r .< Rp] .= g * ɑ * Q / (ρ₀ * cₚ)
bottom_flux =  CuArray(bottom_flux)

# Create boundary conditions
Tbcs = FieldBoundaryConditions(z=ZBoundaryConditions(
    bottom = BoundaryCondition(Flux, bottom_flux)))

# Set up the model and use an artificially high viscosity ν and diffusivity κ.
model = Model(N=(Nx, Ny, Nz), L=(Lx, Ly, Lz), arch=GPU(),
              bcs = BoundaryConditions(T=Tbcs),
              ν=1e-4, κ=1e-4)
```

To accommodate spatially variable boundary conditions, may be `Model` can be split up into a `geometry` component and `dynamics` component?

**Comment by glwagner** [comment]
There is such a split. You should first create the grid, use that to build the boundary conditions, and then pass the grid to the model via Model(grid=grid, ...).

**Comment by ali-ramadhan** [comment]
> However, calling `Model` twice was more memory intensive. I ran into out of memory error. Is the first instance not overwritten when the second instance is defined?

Right yeah, I forgot. There's no GPU garbage collection (although a PR in progress I think) so the memory used up by the first model is never freed until Julia exits...

> There is such a split. You should first create the grid, use that to build the boundary conditions, and then pass the grid to the model via Model(grid=grid, ...).

Yeah that's the proper way to do it.

**Comment by beta-effect** [comment]
> There is such a split. You should first create the grid, use that to build the boundary conditions, and then pass the grid to the model via Model(grid=grid, ...).

Doh, of course. I should have gone in and checked the source earlier. This is much cleaner now:

```julia
# Get location of the cell centers in x, y, z and reshape them to easily
# broadcast over them
G = RegularCartesianGrid((Nx, Ny, Nz), (Lx, Ly, Lz))
xC, yC, zC = G.xC, G.yC, G.zC
xC, yC, zC = reshape(xC, (Nx, 1, 1)), reshape(yC, (1, Ny, 1)), reshape(zC, (1, 1, Nz))

# Set heating flux at the bottom.
Q = 9200  # W/m^2
Rp = 50   # plume radius [m]
r = @. sqrt((xC - Lx/2)^2 + (yC - Ly/2)^2)
bottom_flux = zeros(Nx, Ny, 1)
bottom_flux[r .< Rp] .= g * ɑ * Q / (ρ₀ * cₚ)
bottom_flux =  CuArray(bottom_flux)

# Create boundary conditions
Tbcs = FieldBoundaryConditions(z=ZBoundaryConditions(
    bottom = BoundaryCondition(Flux, bottom_flux)))

# Set up the model and use an artificially high viscosity ν and diffusivity κ.
model = Model(N=(Nx, Ny, Nz), L=(Lx, Ly, Lz), arch=GPU(),
              bcs = BoundaryConditions(T=Tbcs),
              ν=1e-4, κ=1e-4)
```

Passing the grid, `G`, directly to the model does not seem to do anything because it still needs `N` and `L`. May be `N` and `L` could be figured out from `G` if it exists. Although it's a minor change I could try to make this change and send a pull request.

**Comment by glwagner** [comment]
@beta-effect btw using a function may be a better (less code and less memory-intensive) way to impose this boundary condition.

**Comment by glwagner** [comment]
@beta-effect to follow up on my previous comment, here is what I suggest:

```julia
# Variables used as globals in functions must be declared const to work on GPU
const plume_flux = 1e-8 # set to desired temperature flux
const plume_radius = 50
@inline radius(i, j, grid) = @inbounds sqrt((grid.xC[i] - grid.Lx/2)^2 + (grid.yC[j] - grid.Ly/2)^2)
@inline bottom_flux(i, j, grid, args...) = ifelse(radius(i, j, grid) < plume_radius, plume_flux, 0.0)

# Create boundary condition for temperature
Tbcs = HorizontallyPeriodicBCs(bottom = BoundaryCondition(Flux, bottom_flux)))
```

**Comment by glwagner** [comment]
@beta-effect, is your issue solved?

**Comment by beta-effect** [comment]
Yes! Sorry for the late response. Thank you for the concise boundary condition implementation. It works. Closing this issue.
