### ISSUE TITLE
Numerical methods that need to be documented

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#327]
To improve our documentation before submitting something to JOSS I'd like to actually document more of the numerical methods we use.

It would also be good to document everything here in one place (as opposed to merely citing papers) as some of these methods have very little modern documentation online. The only way to understand them is to wade through the original papers which can be frustrating and time consuming.

I already have lots of notes on these in my notebook, just need to typeset it into documentation:
* Direct solution of Poisson's equation on a staggered grid using FFTs [Schumann & Sweet (1988)].
*  How a fast discrete cosine transform is computed on the GPU [Makhoul (1980)]. The 2D fast DCT is especially undocumented anywhere but the paper and was frustrating to implement.
* Operator splitting, how we enforce incompressibility, and how we treat pressure boundary conditions [Orszag, Israeli, & Deville (1986) will be helpful here].
* How Dirchlet, Neumann, and flux boundary conditions are enforced.

Upcoming features that will need to be document. I already have a lot of notes on these:
* Finite volume operators. Will be especially useful to document exactly how the "implicit" no-flux boundary conditions are enforced and which fluxes are zeroed out. This would apply to the rigid lid and channel walls.
* Solving Poisson's equation on a vertically stretched grid with the Fourier analysis cyclic reduction (FACR) algorithm.

**Comment by glwagner** [comment]
LES must be documented too. 

Even more though, the API needs better documentation. We may want to write some tutorial-style pages (like [dedalus](https://dedalus-project.readthedocs.io/en/latest/getting_started.html)) too.

**Comment by ali-ramadhan** [comment]
For the JOSS paper I'll describe these methods referencing the appropriate literature but will leave the transcribing of my notes for another time.

**Comment by glwagner** [comment]
That's probably ok. I think the main requirement for JOSS is a documentation of the *API*, so that people can easily *use* the code. References should be sufficient for numerical methods; detailed documentation with all the math described would be awesome, but is not prerequisite for JOSS publication in my opinion. Perhaps we can set intermediate JOSS goals and longer-term "Oceananigans paper" goals.
