### ISSUE TITLE
Documentation, examples/tutorials, and cleanup for JOSS paper

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#332]
Seems like we just need to clean things up a bit and write 250-1000 words. Might be good to aim for v0.10 to be "JOSS ready".

Seems like we just need to address these three criteria and we're done:
* **Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).** We could probably provide 2 good examples/tutorials based off what we already have. Might be good to have one be a general example (as opposed to an oceanographic example)
* **Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?** This probably needs the most work, but we have some docstrings and I can write more pretty easily. I can also write some pages on general usage.
* **Functionality: Have the functional claims of the software been confirmed?"** Hmmm, are we happy claiming that the package simulates incompressible fluid flows? What else should we confirm? The hardest part might be confirming that the LES closures work.
* A section on how to contribute.

@glwagner we should choose a point to tag v0.10.0 so that documentation can be written up for the v0.10.0 API.

Useful links:
* [Submitting a paper to JOSS](https://joss.readthedocs.io/en/latest/submitting.html)
* [JOSS review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html)
* [Review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html)

**Comment by glwagner** [comment]
> Stratified Couette flow would make a nice example, but I'm slightly against including it as it has to be run at high resolution (or with LES) to get proper results.

Can we use 2D stratified couette flow?

> But we'd have to impose no-slip via a forcing function as y boundary conditions aren't implemented yet

Of course adding this would be done simultaneous to implementing boundary conditions in `y`.

**Comment by glwagner** [comment]
I'd like to discuss examples. Here's a few that I propose:

1. Dramatically simplify internal wave example
2. Free decay of two dimensional turbulence (use x,y plane)

I think we should split deepening mixed layer into a few examples:

3. 2D convection into a stratified fluid, while forcing salinity to obey like a biological tracers (cc @joynryantaylor)

4. More sophisticated 3D deepening mixed layer example with LES.

5. Stratified Couette flow example.

What else?

**Comment by johnryantaylor** [comment]
Hi Greg,
It might be useful to have an example to show how to add a background scalar gradient like in a ‘frontal zone’ simulation (or stirring of a large-scale passive tracer gradient).
John

**Comment by ali-ramadhan** [comment]
I'd like to also two 2D examples

1. rising thermal bubble and
2. lid-driven cavity

as super simple examples. Their set up shouldn't take more than 10 lines excluding comments.

> Dramatically simplify internal wave example

+1! Always good to simplify scripts as much as possible. Would also be nice to include it in the example tests (PR #418) if it can use something like `makeplot = false`.

> Free decay of two dimensional turbulence (use x,y plane)

Only issue with 2D xy-plane simulations is I think things are weird with `Nz=1` so I had to use `Nz=2` (see Taylor-Green vortex test in `test_dynamics.jl`).

1D and 2D models haven't been a priority unfortunately so this sort of stuff has cropped up. I think 2D xz and yz simulations are fine with `Ny=1` and `Nx=1` respectively.

> Stratified Couette flow example.

I can simplify the simulation script from PR #381 down to a 2D example. This one would be good.

> I think we should split deepening mixed layer into a few examples

Sound like a good idea!

**Comment by johncmarshall54** [comment]
I would recommend a baroclinically-unstable channel.

**Comment by ali-ramadhan** [comment]
> I would recommend a baroclinically-unstable channel.

Ah right I did this in the past (PR https://github.com/climate-machine/Oceananigans.jl/pull/301).

Would be easy to convert it into a nice example.
