### ISSUE TITLE
Split JLD2 output files by size

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#344]
Would be good to have a feature that splits JLD2 files by size (e.g. maximum file size of 50 GiB or 100 outputs per file).

Running large simulations right now is risky because the JLD2 files keeps getting appended to so it keeps growing in size (especially since JLD2 does not compress by default) and if the simulation stops/errors/is killed during IO the JLD2 file and all output is corrupted.

We should probably also add an `info=false` flag to `JLD2OutputWriter` that is `false` by default in case a user does not want any JLD2 timings/statistics.

**Comment by glwagner** [comment]
Hmm yeah I agree with the `info` keyword (or `verbose` to match patterns elsewhere?) We should also improve the quality of the information that is outputted when `info=verbose=true`.

An easy improvement could add a field `max_writes` that sets the maximum amount of times a file is written to. After `max_writes` is reached for the current file we can mutate the output writer's `.filepath` to refer to a new file.

More advanced would be the possibility to set a maximum file size.

While we are at it, the `NetCDFOutputWriter` needs a docstring.

dedalus' `FileHandler` should be a good resource:

https://bitbucket.org/dedalus-project/dedalus/src/1b36cc81a600b048ad90253066789af601c8172f/dedalus/core/evaluator.py#lines-306

cc: @kburns
