### ISSUE TITLE
Generalize JLD2OutputWriter

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#357]
We can make some easy improvements to the `JLD2OutputWriter`.

One is to use syntax that permits users to use either a dictionary or a `NamedTuple` for providing their `output_name, output_function` pairs to the output writer. This generalization of the API can be done by changing this line: 

https://github.com/climate-machine/Oceananigans.jl/blob/4c98658b0e27a4a09a556bf2172b640e5d1f1aff/src/output_writers.jl#L228

to 

```julia
data = Dict((name, f(model)) for (name, f) in zip(keys(fw.outputs), values(fw.outputs))
```

or

```julia
data = NamedTuple{Tuple(keys(fw.outputs))}(f(model) for f in values(fw.outputs))
```

(this last would require changing `jld2output!` as well.)

Perhaps list other improvements that might be made at the same time here...

**Comment by ali-ramadhan** [comment]
With PR #344 I'm pretty happy with the JLD2 output writer.

Only gripe is that it's uncompressed output, but I use it for speed so that's fine. Don't think JLD2.jl even offers compression so might be a moot point.

**Comment by glwagner** [comment]
It looks like JLD2 does support compression:

https://github.com/JuliaIO/JLD2.jl/blob/4f8a35e74391fc8433584e11ffe979d1b1575b21/src/JLD2.jl#L201

Would you like to add this is as a feature to the `JLD2OutputWriter`?

**Comment by glwagner** [comment]
I forgot that a `max_writes` option could be useful. That'd be easy to add too.

**Comment by ali-ramadhan** [comment]
Ah nice find! Yeah we can add compression as an option.

Compression is typically more time consuming than I/O which is why the NetCDF output writer was slow (it compresses by default). So I suspect we probably won't typically run with JLD2 compression, although if we do then that's probably a good use for the `async` option so the model isn't waiting for JLD2 compression. Unfortunately, setting up a second CPU worker to do `async` IO is kind of annoying.

**Comment by glwagner** [comment]
Interesting. I was under the impression that for some applications compression can be used to accelerate I/O (due to slow I/O bandwidth and ample CPU resources).

NetCDF may be doing something wrong (cf [this HDF5 post](https://www.hdfgroup.org/2017/05/hdf5-data-compression-demystified-2-performance-tuning/)).

Anyways, it's a bit outside our scope. Maybe the best option here is to provide a `jld2_kwargs` object (or something similar) that allows users to set arbitrary kwargs in `jldopen` (or whatever is appropriate).

**Comment by ali-ramadhan** [comment]
Do you want to close this as PR #382 contained some of these changes?

**Comment by glwagner** [comment]
Yes!
