### ISSUE TITLE
Purpose of Diagnostic abstract type?

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#361]
An abstract type called `Diagnostic` is defined here:

https://github.com/climate-machine/Oceananigans.jl/blob/66670ad782b66db7906d407ab9217ec0f26a7bb2/src/Oceananigans.jl#L200

but does not seem to be useful for dispatch anywhere. What is its purpose?

**Comment by ali-ramadhan** [comment]
Right. It serves the same purpose as the `OutputWriter` abstract type. It's dispatched on for functions like `run_diagnostic` and `time_to_run` in PR #352.

https://github.com/climate-machine/Oceananigans.jl/blob/908ae4d23ce3e472d03fd69766edc457301df681/src/diagnostics.jl#L6

We did agree to refactor the diagnostics abstraction anyways, so maybe the need for an abstract `Diagnostics` type will disappear.

I might hold off on this issue until it's clearer what `diagnostics.jl` will look like.

**Comment by glwagner** [comment]
Right, but `run_diagnostic` cannot receive arguments that are not of type `Diagnostic`, because the elements of `model.diagnostics` are restricted to this type a priori. Similarly for `time_to_run`.

Good point about `OutputWriter` --- perhaps this abstract type is also superfluous?
