### ISSUE TITLE
Boundary condition API kernels should use dynamic launch configuration

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#363]
Kind of a leftover relic I forgot to cleanup, but boundary condition API kernels still use the old `Tx, Ty` and `Bx, By, Bz` values to launch kernels.

We should switch them to use dynamic launch configuration like all the other time stepping kernels.

**Comment by glwagner** [comment]
Go for it!

**Comment by ali-ramadhan** [comment]
Will do. Just opened the issue before I forgot about this.

Especially important if we want to extend the boundary conditions API to x and y.

**Comment by glwagner** [comment]
Why is it especially important for that?

**Comment by ali-ramadhan** [comment]
Good to clean up the API first before extending it. Otherwise we'd have multiple definitions of `Tx ,Ty, Tz, Bx, By, Bz` floating around, one set for each dimension.

**Comment by ali-ramadhan** [comment]
This was fixed at some point a while back.
