### ISSUE TITLE
Is it possible to add additional (passive) tracers?

### ISSUE THREAD

**Issue by astrotuna201** [climate-machine/Oceananigans.jl#369]
Dear Oceananigans team,

this looks like a really exciting and useful project. As an external user, how flexible is this package to add, e.g. , additional (passive) tracers to a model? I see that there is a generalised array of tracers, but temperature and salinity are hardcoded into the model initialiser. Would it be possible to add more tracers? I am asking because eventually it would be super cool to use a tool like this as the ocean circulation component in other Earth System Models. I am currently using [cGenie](https://github.com/derpycode/cgenie.muffin) which internally uses this ocean model : https://www.geosci-model-dev.net/4/957/2011/ ...
What is the general scope to do something like this? 
Sorry for asking user-level questions in the Issues, but I think you are still working on some more detailed documentation ...

Many thanks! Heiko

**Comment by glwagner** [comment]
@astrotuna201, at the moment it is not possible to add passive tracers, but this functionality is definitely on our mind! We are currently focusing on verifying the LES model against results in the literature and from direct numerical simulation. But arbitrary systems of passive tracers is a feature we would like to add once this verification phase is complete.

As for the second part of your question: we have focused thus far on developing the model for large eddy simulation using GPUs. However, ambition does exist to develop Oceananigans into a full-fledged ocean model.

You may also be interested in the ocean model whose development is planned for the [Clima](https://github.com/climate-machine) project. This model will also be written in julia and will use a discontinuous Galerkin spatial discretization scheme (as opposed to the finite volume method used by Oceananigans).
