### ISSUE TITLE
Model constructor not general enough + different model constructors for different use cases

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#372]
To enable checkpoint restoration for large models, we need to revise the model constructor so that `velocities` and `tracers` can be passed as keyword arguments.

In addition, I think it might make sense to remove `N`, `L`, and the viscosities from keyword arguments, so that all of the constructor arguments in the *base* model constructor correspond to subfields of `Model`.

At the same time and for user convenience, we should add new constructors (perhaps something like `SimpleModel` or `BasicModel`) that *do* have keyword arguments for `N`, `L`, etc. 

Through this method we can provide both convenience for users looking for simple and basic functionality while also cleaning up the *base* model constructor for the purpose of checkpointing, code cleanliness, and easier usage for advanced users. We will probably want to remove `N` and `L` from the model constructor anyways when we have more than one type of grid for a user to choose.

**Comment by ali-ramadhan** [comment]
I think a `NonDimensionalModel` will be useful for certain tests, although I guess there's more than one way to non-dimensionalize.

**Comment by glwagner** [comment]
Probably something we could add when we have arbitrary tracers, because in that case we could have a buoyancy tracer...
