### ISSUE TITLE
Minor performance regression (more memory allocations)

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#397]
There seems to be some performance regression as we now perform tons of little memory allocations somewhere. Model still time steps as fast as it should so we probably haven't noticed it as we run large model sizes where this allocations are kind of hidden.

Seems like mainly a CPU issue.

CPU: 
```
julia> using Oceananigans

julia> model = Model(N=(128, 128, 128), L=(1, 1, 1));

julia> @time time_step!(model, 1, 1)
 16.614982 seconds (34.03 M allocations: 1.775 GiB, 6.86% gc time)

julia> @time time_step!(model, 1, 1)
  0.738576 seconds (1.31 M allocations: 264.089 MiB, 3.97% gc time)
```

GPU:
```
julia> using Oceananigans

julia> model = Model(N=(256, 256, 256), L=(1, 1, 1), arch=GPU());

julia> @time time_step!(model, 1, 1);
 28.425740 seconds (71.04 M allocations: 3.383 GiB, 10.72% gc time)

julia> @time time_step!(model, 1, 1);
  0.025893 seconds (8.90 k allocations: 978.531 KiB)
```

**Comment by ali-ramadhan** [comment]
Hmmm yeah @glwagner points out in #402 that it may be the halo filling causing this regression.

My guess is that we need `@inline` for all the halo filling functions. This would only manifest as an issue on the CPU but the GPU `@inline`s by default in many cases.

I'll benchmark on a branch and open a PR if it's this easy.

**Comment by glwagner** [comment]
The difference definitely suggests a missing `@inline` in some kernel function, somewhere. Note that the halo filling functions are not kernel functions (instead, they launch kernels) so we should not have to `@inline` them.

**Comment by ali-ramadhan** [comment]
This was fixed and we must have forgotten to close this issue, although a missing `@inline` is probably also the reason for #675.
