### ISSUE TITLE
Grids should allow us to specify the domain

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#413]
Right now `RegularCartesianGrid` forces you to use `x = [0, Lx]`, `y = [0, Ly]`, and `z = [-Lz, 0]` but would be good to be able to specify the interval manually.

This will also allow the user to pick whether the vertical coordinate is negative or positive.

**Comment by glwagner** [comment]
Add a keyword argument called x0 that accepts a tuple which specifies the origin of the coordinate system.

**Comment by ali-ramadhan** [comment]
Hmmm, since we're making lots of breaking changes to the API already would it be a good idea to replace the `L` kwarg with `x`, `y`, and `z` kwargs?

So now the domain must be specified, not just the lengths?
```julia
grid = RegularCartesianGrid(N=(32, 32, 16), x=(0, Lx), y=(0, Ly), z=(-Lz, 0))
```

**Comment by glwagner** [comment]
Hmm. I'm okay with that. However, I was suggesting

```julia
grid = RegularCartesianGrid(N=(32, 32, 16), L=(Lx, Ly, Lz), x₀=(0, 0, -L[3]))
```

which is a little less writing for users who don't care where their origin is. What you've proposed is more explicit though (closely resembles what dedalus does).

**Comment by glwagner** [comment]
Could also use `X₀` for the origin (keeping with the apparent emerging convection that tuples / vectors are denoted by capital letters...)

**Comment by ali-ramadhan** [comment]
Hmmm, I personally find
```julia
x₀=(0, 0, -L[3])
```
a little less readable than
```julia
x=(0, Lx), y=(0, Ly), z=(-Lz, 0)
```
but my suggestion will introduce breaking changes while yours won't (although right now seems like a good time to introduce breaking changes).

@suyashbire1 any thoughts?

**Comment by suyashbire1** [comment]
Since our intention is to make the code as readable as possible, I'd prefer `x=(0, Lx), y=(0, Ly), z=(-Lz, 0)`. We could also use Julia's built-in ranges, which are even more readable.

**Comment by ali-ramadhan** [comment]
I can add `x, y, z` kwargs to `RegularCartesianGrid` but keep a legacy constructor that does `x=(0, L[1]), y=(0, L[2]), z=(-L[3], 0)` by default.

Would be nice to get this into the stratified Couette flow experiment as `z = (-h, h)` in there which complicates the analysis scripts a little bit.

**Comment by glwagner** [comment]
The suggestion here is to require users to explicitly define `x`, `y`, and `z`? Would users still have to define all three for two-dimensional domains?

I understand the benefit in terms of being explicit, but I'm worried there are a lot of use cases in which the origin of the domain is simply unimportant, and the only relevant parameter is the domain extent. 

Is there any concern about confusion between specifying the domain in terms of bounding cell faces versus cell centers?

**Comment by ali-ramadhan** [comment]
Just opened a PR with this, we can discuss what's the best approach.

> Would users still have to define all three for two-dimensional domains?

Ideally no. I can modify `RegularCartesianGrid` to take this into account.

> I understand the benefit in terms of being explicit, but I'm worried there are a lot of use cases in which the origin of the domain is simply unimportant, and the only relevant parameter is the domain extent.

The legacy constructor `RegularCartesianGrid(N, L)` can still be used in this case.

> Is there any concern about confusion between specifying the domain in terms of bounding cell faces versus cell centers?

I don't think so. When specifying the domain size, you are in effect specifying the location of the first and last face. All cell centers are located strictly between the first and last cell interface. I don't think it makes sense to specify the domain via the cell centers.
