### ISSUE TITLE
Checkpointer warning if properties included make restoring impossible

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#417]
Right now the `Checkpointer docstring says

```
Note that extra model `properties` can be safely specified, but removing
crucial properties such as `:velocities` will make restoring from the
checkpoint impossible.
```

Would be good to print a warning if something crucial is missing from `properties`.

**Comment by glwagner** [comment]
How about adding them automatically, coupled with emission of an `@info` or `@warn`?
