### ISSUE TITLE
`time_step!` function for adaptive time stepping

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#431]
Would be nice to be able to pass a `TimeStepWizard` to `time_step!` and have it take care of updating the time step and time stepping until `end_time`.

**Comment by glwagner** [comment]
Probably something to implement when we have a time stepper that’s more appropriate for adaptive time stepping like RK3?

**Comment by glwagner** [comment]
One thought: we can create a ‘Simulation’ type with a ‘run!’ function, and fields model, timestep (either constant or a Wizard) and perhaps also a progress statement function for managing a simulation.

**Comment by ali-ramadhan** [comment]
> Probably something to implement when we have a time stepper that’s more appropriate for adaptive time stepping like RK3?

Yeah that makes sense. We could implement a initializer for AB2 that is formally second-order, e.g. RK2, trapezoidal, or Ralston's method (I think these are all RK2 schemes anyways). But maybe not worth it as AB2 isn't great with adaptive time-stepping.

> One thought: we can create a ‘Simulation’ type with a ‘run!’ function, and fields model, timestep (either constant or a Wizard) and perhaps also a progress statement function for managing a simulation.

Think I saw a more detailed proposal in another issue so I'll comment there.

**Comment by ali-ramadhan** [comment]
This functionality has been implemented with the simulation type from PR #621.
