### ISSUE TITLE
Make progress statements a part of `time_step!`

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#432]
Instead of having us manually print a progress statement in a `while` loop, maybe we can pass a `progress_message(model)` function to `time_step!` that does this.

This should help clean up the scripts a lot, and we could provide a couple of reasonable defaults instead of setting up this functionality in every script.

Eventually the `progress_message(model)` function can be made fancy as we wish with unicode plots, a curses interface for complex progress output, or even email updates.

**Comment by glwagner** [comment]
This can also be done with a diagnostic?

**Comment by asinghvi17** [comment]
If you want to integrate with the Julia "progress bar" system, you could put in something like:
```julia
@debug "this is a short description of my loop" progress=iteration/length_of_loop
```

This works in Juno, and with MicroLogging.jl in the REPL.

**Comment by ali-ramadhan** [comment]
@glwagner True, we should just make use of the existing infrastructure. We don't have to call it a monitor but seems like this diagnostic would be closer in spirit to `NaNChecker` than `HorizontalAverage`.

We might want to have some way of accessing the `TimeStepWizard` from the diagnostic though. Although this could probably be done with an anonymous function.

@asinghvi17 Thanks for the tip! Had no idea you could pass a `progress` kwarg to logging macros. Will have to check it out along with #71

**Comment by glwagner** [comment]
It could make sense to have a `Simulation` type for managing time stepping, including progress messages / utilities for logging output from diagnostics and maybe also plotting, eg

```julia
simulation = Simulation(model, dt, stop_time=8day, wall_time_limit=1day, progress=ProgressMessenger(diags=diags), ...)

run!(simulation)
```

**Comment by ali-ramadhan** [comment]
I think we agreed that making pretty progress statements with UnicodePlots is not a good use of our time, but just to document the possibilities, here are a couple of packages for pretty printing traces:

https://github.com/jagot/SolverTraces.jl
https://github.com/c42f/TerminalLoggers.jl
