### ISSUE TITLE
Use `FT` for "floating point type"

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#446]
In various parts of the code we use either `T` or `FT` to indicate the floating point type (eg, `Float64` or `Float32`).

We should use `FT` consistently, as `CLIMA` will:

https://github.com/climate-machine/CLIMA/pull/461

**Comment by ali-ramadhan** [comment]
Hmmm, yeah I think `T` is still used in the `Operators` module. I'll make sure to use `FT` from now on, and we can close this when we've used `FT` everywhere.
