### ISSUE TITLE
Logic for arguments to time-stepping related functions

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#448]
Our time-stepping functions / kernels in `time_steppers.jl` are a bit chaotic with long argument lists, etc. To bring order to this world, it might be a good idea to adopt some kind of convention / preferred ordering to the function arguments. 

Almost all of the functions are mutating, so I think the first argument(s) should be the objects that are mutated by the function. This follows the [julia style guide recommendation](https://docs.julialang.org/en/v1/manual/style-guide/index.html#Write-functions-with-argument-ordering-similar-to-Julia-Base-1).

After that, the style guide doesn't offer guidance though it could make sense to put important objects for dispatch first (mostly `arch`). 

The rest of the objects fall into a few categories (I think):

* grid
* parameter structs
* `NamedTuple`s of fields / arrays / boundary conditions
* scalars

Perhaps we can use an ordering along the lines of

1. object being mutated
2. architecture (if used)
3. grid (if used)
4. scalars
5. parameter structs
6. `NamedTuple`s of stuff

I'm open to other patterns too.

**Comment by ali-ramadhan** [comment]
I agree we should pick a convention and stick to it. I'll think more about this the next time I'm refactoring `time_steppers.jl`. But your proposed ordering looks good to me!
