### ISSUE TITLE
Use multiple dispatch to control Poisson solver

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#45]
[This `if`-statement](https://github.com/ali-ramadhan/Oceananigans.jl/blob/e1be1f0e3f067cdb4236eb5e7b962e0c772ce4d1/src/time_steppers.jl#L140) is not necessary, because the architecture can be known from the array types of the `CellField`s.

Specifically, [this line](https://github.com/ali-ramadhan/Oceananigans.jl/blob/e1be1f0e3f067cdb4236eb5e7b962e0c772ce4d1/src/spectral_solvers.jl#L389) can be changed to

```
function solve_poisson_3d_ppn_planned!(ssp::SpectralSolverParameters, g::RegularCartesianGrid, f::CellField{T}, ϕ::CellField{T}) where T<:CuArray

...

end
```

I think it would actually be preferable to dispatch on the type of the arrays in `RegularCartesianGrid`. However, it does not appear that the arrays representing the coordinates of the grid are parameterized in [the definition of `RegularCartesianGrid`](https://github.com/ali-ramadhan/Oceananigans.jl/blob/e1be1f0e3f067cdb4236eb5e7b962e0c772ce4d1/src/grids.jl#L12). Why is that? 

If the array type of the problem is part of `RegularCartesianGrid`, then dispatch can be used in place of `if`-statements all over the code, especially in `fields.jl`.

Finally, the term 'spectral solvers' is misleading here. The solver does not have spectral accuracy; it simply uses the FFT, which *happens* to be used to solve different problems that have a 'spectral' character.

**Comment by ali-ramadhan** [comment]
Thanks for looking through the time stepping code, this is great feedback!

I agree it would be nice to dispatch on the array type (or even the architecture, another reason to use types instead of symbols).

No reason why `xC, xF, yC, ...` have no assigned type in `RegularCartesianGrid`, just oversight on my part.

There will probably be a major refactor of the code's design soon-ish to get all this little stuff right.

I remember fields initially had the array type be a parameter, e.g. `CellField{T}` then `data::T` but I hit some performance issues with that I think. I may have just been encountering the [Avoid fields with abstract containers](https://docs.julialang.org/en/v1/manual/performance-tips/index.html#Avoid-fields-with-abstract-containers-1) Julia performance tip, but I think making the parameter an `AbstractArray` as you're suggesting shouldn't sacrifice performance.

And yes, the solver is not spectral. Will probably generically call it `PoissonSolver` when the next refactor happens (and the documentation would make it clear what it actually does).

**Comment by glwagner** [comment]
But currently the array type *is* a parameter in the [`CellField` definition](https://github.com/ali-ramadhan/Oceananigans.jl/blob/6ec7cc23393bd5fdce846e1b3eb601fcd1901af4/src/fields.jl#L12).

I am referring to the [constructor for `CellField`](https://github.com/ali-ramadhan/Oceananigans.jl/blob/6ec7cc23393bd5fdce846e1b3eb601fcd1901af4/src/fields.jl#L71) (for example), which use branches rather than multiple dispatch to construct fields with different array types. It's not a huge deal, but I think using multiple dispatch is cleaner and easier to extend than using branches and `metadata`.

You may not even need `metadata` to be an attribute of the fields, or the model. The fact that a GPU architecture is being used can be inferred from the type of the coordinate arrays and FFT plans and whatnot.

**Comment by ali-ramadhan** [comment]
Wow obviously I forgot what the code even looks like...

That is a better idea, multiple dispatch always feels cleaner than if statements. I didn't think of just using the array type, which is really what matters.

**Comment by glwagner** [comment]
Let's start with the constructor for `Model`. Where is that?

**Comment by ali-ramadhan** [comment]
https://github.com/ali-ramadhan/Oceananigans.jl/blob/6ec7cc23393bd5fdce846e1b3eb601fcd1901af4/src/model.jl#L22

**Comment by glwagner** [comment]
Ok, here is what I propose:

1. Change the arguments of the `Model` constructor to accept an `array_type` keyword, which currently will be `CuArray`.

2. Change the format of the Grid constructor so that `array_type` and `float_type` are explicit arguments (for convenience you could also provide a keyword constructor for users who wish to construct grids outside of `Model` generation)

3. Change the definition of `Grid` so that both the `float_type` and the `array_type` are parameters.

4. Run multiple dispatch on the constructor for `Grid` for various array types. Also create a 'dummy' constructor that throws an error when an unknown `float_type` or `array_type` is passed.

5. Use the parameters of `Grid` to construct fields.

`metadata` on architecture type is then probably not necessary. This will also generalize the code, since arbitrary array types may be desired in the future (`MPIArray`, `CLArray`, etc). All we do is enforce the logical requirement that all data stored in arrays must use the same array type.

In addition to this, the algorithms for the Poisson solver should not be different between GPU and CPU. The same syntax can be used with CuFFT plans as with FFTW plans. The only place where multiple dispatch need be used is in the preparation of the plans.

**Comment by glwagner** [comment]
I can help with some of this. You can avoid code replication by writing a 'translator' function for the GPU case --- you can use the ordinary `Grid` constructor to build a `Grid` object on the CPU, and then in a line or two 'translate' that object into an object with CuArrays.

See, for example, the [strategy employed by `CuGeophysicalFlows.TwoDTurb`](https://github.com/FourierFlows/CuGeophysicalFlows.jl/blob/a5eb6a84cedbe2c120d40a9c8335812e2cc28205/src/twodturb.jl#L52).
