### ISSUE TITLE
Use less defaults in model construction?

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#459]
@johncmarshall54 suggested it might be a bit dangerous to assume default boundary conditions, so they should always be specified.

Worth discussing as this might apply to other model properties too.

A common question for simple model setups is "what are the boundary conditions?".

**Comment by glwagner** [comment]
I am fine either way. Documentation is the important part in my opinion. In general, I think defaults are important for useability. However, if using a default isn't helpful for useability, then I agree it should be avoided.
