### ISSUE TITLE
Merge `Oceananigans.Operators` with `closure_operators.jl`

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#460]
Would be good to do this. Might follow PR #283

**Comment by glwagner** [comment]
I thought this was in the works for finite volume operators?

By the way, I am now officially opposed to using "iota" for interpolation. It just looks too much like `i`. I think we should stick with the triangle. Its distinct, meaningful, and readable.

**Comment by ali-ramadhan** [comment]
This was done in PR #529.
