### ISSUE TITLE
Benchmark scripts should report CPU and GPU being used

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#466]
Would be helpful in giving content to any benchmarks produced.

Probably also useful to include Julia `versioninfo()`, CUDA version maybe, other systems specs, MPI version, etc.

**Comment by arcavaliere** [comment]
I'd like to take a crack at this!

**Comment by ali-ramadhan** [comment]
Ah sorry for the slow reply @arcavaliere but I think I accidently ended up doing this last week as part of PR #570 and forgot to reference this issue! 

@arcavaliere What sort of stuff are you interested in helping out with or learning more about?

PS: Are you the [Julia Slack](https://slackinvite.julialang.org/)? Might be easier to discuss stuff on there.

**Comment by arcavaliere** [comment]
@ali-ramadhan I am on the Julia Slack. I'm Alex Cavaliere on there.
I'd love to learn about and work on the models. I'm also happy doing more infrastructure work!
