### ISSUE TITLE
The dreaded interpolation operator

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#469]
We should pick a symbol to denote interpolation that we're all happy with. This is proving to be quite difficult unfortunately...

So right now `Oceananigans.Operators` uses `avg_` to denote an interpolation operator which will be wrong once #283 is merged, but is also too verbose.

`closure_operators.jl` uses `▶` (`\blacktriangleright`) which @glwagner likes but @christophernhill does not. I also don't really like it as it takes a while to type, and is actually quite hard to figure out and remember `\blacktriangleright`. I also think it's too much bold and sticks out too much when reading through the code.

In PR #283 I went with `ϊ` (`\iota\ddot`) which I now agree isn't great, so @thabbott and @RaphaelRR suggested `ι` (`\iota`) for interpolation, which I quite like. But @glwagner isn't a huge fan.

I've spent a lot of time looking through the unicode tables to try and find something else but to no avail. My favorite find is `↪` (`\hookrightarrow`) but it's reserved for binary operations.

Apologies to anyone who thinks this is the most pedantic issue.

**Comment by glwagner** [comment]
If the problem with \blacktriangleright is time-to-type and too much bold, then you might like \triangleright instead, eg

```julia
▷a
```

\iota is extremely similar to `i` --- doesn't this look funny?

```julia
ιa(i, j, k, grid)
```

I prefer something more distinctive and therefore readable, like

```julia
▷a(i, j, k, grid)
```

When I chose the triangle I considered many arrow-like possibilities, but they either seemed too small (hard to read), or were not valid julia symbols.

**Comment by christophernhill** [comment]
Maybe we should have some sort of slam down soon? Someone presents each case, we all vote and then we all accept whatever the outcome of vote is and move on?

**Comment by ali-ramadhan** [comment]
I'm down for a democratic slam down.

I do agree with @glwagner that `ι` is a little similar to `i` and I also think it's too small when you want something that stands out more.

I quite like `▷`.

To me this code looked kind of busy and the `▶` character sticks out too much
![image](https://user-images.githubusercontent.com/20099589/66708607-fcf28780-ed20-11e9-8269-64c1630a7d58.png)
so this looks a lot better in my opinion:
![image](https://user-images.githubusercontent.com/20099589/66708610-0ed42a80-ed21-11e9-8226-8946f795bccc.png)

**Comment by christophernhill** [comment]
OK - my recollection is that capital iota (\Iota\ddot) with double dot gave a unicode error, that was
why I went with lower case?  
I have a feeling Julia 1.3 has some fixes/additions to unicode features - so possibly \Iota\ddot could be a candidate too?

**Comment by ali-ramadhan** [comment]
`Ϊ` (`\Iota\ddot`) works for me but might be the same as `Ï` (`I\ddot`). They look the same (on my computer at least).

https://github.com/JuliaLang/julia/blob/v1.3.0-alpha/NEWS.md

Got excited that Julia 1.3 supports Unicode 12.1 but apparently that's only one extra character haha.
