### ISSUE TITLE
LES regression test

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#473]
Seems like a good idea to have an LES regression test for big PRs that modify the `TurbulenceClosures` module such as PR #452.

I guess we can use a coarse stratified Couette flow or free convection simulation in steady state to check for this.

**Comment by glwagner** [comment]
The `ocean_wind_mixing_and_convection.jl` example uses an LES closure. I think just copy and pasting that into a regression script would work.
