### ISSUE TITLE
Output example for NetCDF errors

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#499]
The `netcdf_output_example.jl` throws an error because `OWClose` is not defined. I also think that the constructor for the output writer may have incorrect keywords:

https://github.com/climate-machine/Oceananigans.jl/blob/27493f3682e4996af2e2abf4be240abe6384a3fd/examples/netcdf_ouput_example.jl#L44

**Comment by suyashbire1** [comment]
Thanks for noticing these. WIll fix them today.
