### ISSUE TITLE
Grid should encode whether positive means east, north, etc.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#50]
John suggested it would be nice if this kind of metadata is kept track of in the grid structs.

**Comment by christophernhill** [comment]
A mapping between index and base coordinate system is what we typically use.  Base coordinate system can be geographic lat-lon, or could be cylindrical polar for some process studies). We probably do want to keep flexibility in the mapping, but we do want an easy route to understand the mapping.

**Comment by glwagner** [comment]
You could implement this idea with a new type family (something like `BaseCoordinateSystem`) that organizes information about the base coordinate system and permits dispatch for functions like `get_base_coordinates(grid)`, for example. The `BaseCoordinateSystem` could be both an attribute of `Grid` and a type parameter in the Grid definition. This would also allow identity mappings for idealized grids that don't have a meaningful base coordinate system.

**Comment by ali-ramadhan** [comment]
Closing as I think we've basically done this with boundary conditions.
