### ISSUE TITLE
`Ωᵉᵃʳᵗʰ` default for Coriolis constructors?

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#510]
We also use `gᴱᵃʳᵗʰ` in the buoyancy constructors. It could also make sense to use Earth's rotation rate as a default in the `FPlane` constructor, eg:

```julia
const Ωᴱᵃʳᵗʰ = 7.2921e-5 # https://en.wikipedia.org/wiki/Earth%27s_rotation#Angular_speed
# ...
function FPlane(FT; f=nothing, latitude=nothing, rotation_rate=Ωᴱᵃʳᵗʰ)
# ...
```

**Comment by ali-ramadhan** [comment]
I agree we should use it as a default and define it as a `const`. But I like to keep superscripts for notation (mostly because the entire alphabet isn't available as superscripts or subscripts) so in this case I might instead use the variable name `Ω_Earth`.
