### ISSUE TITLE
Ranges are `Float64` even if `FT=Float32` is passed to `RegularCartesianGrid`

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#544]
Was adding some grid tests and noticed this. Will fix as part of PR #543.

```julia
julia> grid = RegularCartesianGrid(Float32; size=(10, 10, 10), length=(1, 1//7, 2π))
julia> eltype.([grid.xF, grid.yF, grid.zF, grid.xC, grid.yC, grid.zC])
6-element Array{DataType,1}:
 Float64
 Float64
 Float64
 Float64
 Float64
 Float64
```

**Comment by ali-ramadhan** [comment]
Somewhat related but
```julia
julia> range(10f0, 20f0, length=5) |> typeof
StepRangeLen{Float32,Float64,Float64}
```
so even if `eltype` is `Float32`, `Float64` values may be used to store the step sizes to produce a range that is "free of roundoff error" (see `help?> StepRangeLen`).

To avoid mixing precisions I wonder if it's better to move from ranges to 1D arrays (tiny memory storage cost but guaranteed to not mix different precision).

**Comment by glwagner** [comment]
What's wrong with using a twice-precision step size?

The advantage of ranges is that they are a lot faster --- this is why such attention was paid to ranges in designing them in julia base. This affects simulations that use coordinates in GPU kernels. We probably should have a very good reason for using arrays when there are clear advantages to ranges, eg arrays should improve the experience of most users (I don't see why it matters).
