### ISSUE TITLE
Should `Model` be renamed to `IncompressibleModel` or `BoussinesqModel`?

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#566]
I guess `BoussinesqModel` is a subset of `IncompressibleModel`? Maybe `BoussinesqModel` is only true if you're running with tracers. If you're running with zero tracers then there's no buoyancy per se.

**Comment by glwagner** [comment]
Are we anticipating having more than one model?

There’s a few possible designs. For example, we could abstract the “equation”, rather than the model.

**Comment by glwagner** [comment]
If we have Compressible than Incompressible makes sense. But if we have QGModel, then Boussinesq makes more sense. Our choice depends on the models available.

**Comment by johncmarshall54** [comment]
I would say incompressible. Essential assumption is divv=0. We can have a
non-Boussinesq incompressible model by going in to pressure coordinates.
This would be one version of a family of incompressible models. Ali also
has an incompressible version. So to me a compressible/incompressible
naming fork makes sense.

**Comment by glwagner** [comment]
I think @johncmarshall54's stance is sensible. It's more likely we will have non-Boussinesq and compressible models than a QGModel.

**Comment by ali-ramadhan** [comment]
Sorry for the slow reply. Indeed I was thinking of introducing a `CompressibleModel` type but will open another issue about it.
