### ISSUE TITLE
More performant mod1 functions.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#57]
@vchuravy suggested using if-else statements instead of
```julia
@inline incmod1(a, n) = a == n ? one(a) : a + 1
@inline decmod1(a, n) = a == 1 ? n : a - 1
```
as it might be faster on the GPU. Also worth checking out Julia's `mod1(x, y)` function.

I'll test a bunch of different mod1 functions once we have the algorithm fully working on the GPU.

See also: [/r/Julia/Efficient wrap-around with 1-based indexing?](https://www.reddit.com/r/Julia/comments/6hhryc/efficient_wraparound_with_1based_indexing/)

**Comment by vchuravy** [comment]
Specifically `ifelse(a==1, n, a - 1)`. This should always be faster than `mod`. In ShallowWaterBench, we consciously choose to use OffsetArrays, to avoid any wrap around and implement ghost cells.

**Comment by glwagner** [comment]
Wasn't this solved?

**Comment by ali-ramadhan** [comment]
Yes. Thanks for pointing this out!
