### ISSUE TITLE
`TemperatureBuoyancy` for evolving temperature without salinity

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#581]
Would be useful to speed up simulations that use temperature but not salinity.

Should be easy to implement now that we have arbitrary tracers.

**Comment by glwagner** [comment]
A thought: 

A different design would extend `SeawaterBuoyancy` with two types that specify whether temperature and salinity are present:

```julia
struct SeawaterBuoyancy{FT, EOS, T, S} <: AbstractBuoyancy{EOS}
    gravitational_acceleration :: FT
    equation_of_state :: EOS
end
```

and

```julia
function SeawaterBuoyancy(FT=Float64;
                          gravitational_acceleration = g_Earth,
                          equation_of_state = LinearEquationOfState(FT)
                          with_temperature = true, with_salinity = true
)
    return SeawaterBuoyancy{FT, typeof(equation_of_state), with_temperature, with_salinity}(gravitational_acceleration, equation_of_state)
end
```

We can then dispatch on those types when calculating buoyancy.

Slightly less code this way, but perhaps the complexity isn't worth it.

**Comment by glwagner** [comment]
Looking at the issue again, I'm liking the solution I've proposed because I think it's easier to understand for users. Any thoughts?
