### ISSUE TITLE
Convert Grid and Field structs to isbitstype

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#59]
@peterahrens suggested removing `ModelMetadata` from `Field` structs and make the `Grid` a parameter, i.e. `Grid{T,G}` then it should be isbitstype. It's not isbits right now because T<:AbstractArray.

Then we should be able to use some abstractions in the CPU/GPU element-wise kernels as well as multiple dispatch and won't need to have `δx_c2f`, `δx_f2c`, `δx_e2f`, `δx_f2e`, etc.

Some goals for guidance:
- [ ] Prototype grid and field types that are `isbitstype`.
- [ ] Test that they do work with GPUifyLoops on the GPU. For this I will extend the example from https://github.com/vchuravy/GPUifyLoops.jl/pull/18
- [ ] Benchmark the simple example to see things slow down. I don't expect to see much of a difference.
- [ ] Refactor the operators and time stepping loop to use the new abstractions!
- [ ] Add tests to make sure any structure that may be passed to a CUDA kernel `isbitstype`. Just construct a bunch of grids, fields, and forcing functions and test that they are indeed `isbitstype`.
- [ ] Benchmark the model with `isbitstype` abstractions to make sure performance hasn't degraded.

**Comment by glwagner** [comment]
Note that [the definition of `Grid`](https://github.com/ali-ramadhan/Oceananigans.jl/blob/f7ba1ce353eaa6abc2b3c9381fa22fe53ba27fce/src/grids.jl#L12) also needs to modified.

**Comment by vchuravy** [comment]
Was about to note the same thing: https://github.com/ali-ramadhan/Oceananigans.jl/blob/f7ba1ce353eaa6abc2b3c9381fa22fe53ba27fce/src/grids.jl#L33-L46 need to be typed to be isbits.

**Comment by glwagner** [comment]
Perhaps move this to v0.6?

**Comment by ali-ramadhan** [comment]
Agreed.

**Comment by glwagner** [comment]
@jm-c and I talked today and we have an additional point to make (this is related to #115 as well).

Notice first that the [operators `δz_f2c` and `δz_e2f`](https://github.com/glwagner/Oceananigans.jl/blob/3307031283dab154d32c071c47d9e275f1a6e17e/src/operators/ops_regular_cartesian_grid.jl#L29) are identical:

```julia
@inline function δz_f2c(f, Nz, i, j, k)
    if k == Nz
        @inbounds return f[i, j, k]
    else
        @inbounds return f[i, j, k] - f[i, j, k+1]
    end
end

@inline function δz_e2f(f, Nz, i, j, k)
    if k == Nz
        @inbounds return f[i, j, k]
    else
        @inbounds return f[i, j, k] - f[i, j, k+1]
    end
end
```

Our solution:

```julia
abstract type Location end
struct Center end
struct Interface end

struct Field{Lx, Ly, Lz, A, G}
    data::A
    grid::G
end
```

we then need only two `δz` functions that dispatch on `Lz`; for example:

```julia
δz(f::Field{Lx, Ly, Lz}, i, j, k) where {Lx, Ly, Lz<:Center} = ...
δz(f::Field{Lx, Ly, Lz}, i, j, k) where {Lx, Ly, Lz<:Interface} = ...
```

**Comment by ali-ramadhan** [comment]
Dispatching on the location as a parameterized type looks neat, would definitely clean things up! Thanks for coding up the example.

I see how this would clean things up for `δz_f2c` and `δz_e2f` but the δz operator also needs to know onto which location to interpolate, so how would this work with `δz_f2c` and `δz_f2e`?
```julia
@inline function δz_f2c(f, Nz, i, j, k)
    if k == Nz
        @inbounds return f[i, j, k]
    else
        @inbounds return f[i, j, k] - f[i, j, k+1]
    end
end

@inline function δz_f2e(f, Nz, i, j, k)
    if k == 1
        return 0
    else
        @inbounds return f[i, j, k-1] - f[i, j, k]
    end
end
```

To me it looks like they both fit
```julia
δz(f::Field{Lx, Ly, Lz}, i, j, k) where {Lx, Ly, Lz<:Interface} = ...
```
so I'm not sure how dispatch between the two.

**Comment by glwagner** [comment]
“face to edge” delta z must refer to an operation on an x-interface or
y-interface — not a z-interface to an edge?

**Comment by ali-ramadhan** [comment]
Ah yes I remember @jm-c's concern now! Yes, just "face" and "edge" are ambiguous.

So your proposed solution will make it explicit exactly which interface the field is being interpolated from and to, which will be nice.

**Comment by glwagner** [comment]
An “edge” is the case in which 2 of Lx, Ly, or Lz are “interface”. We just
don’t need special notation. This method of specifying locations in a cube
is simpler, but also more general.

**Comment by ali-ramadhan** [comment]
I'm finally starting to work on this issue now. I should be able to refactor all the code without changing any of the numerics. Resolving this issue will also resolve #60.

I have moved the slightly separate issue of just using cell centers and cell interfaces (and explicitly stating which interface) to #146 as that change will change the operators and numerics, and may be trickier to get right.

Some goals for guidance:
- [ ] Prototype grid and field types that are `isbitstype`.
- [ ] Test that they do work with GPUifyLoops on the GPU. For this I will extend the example from https://github.com/vchuravy/GPUifyLoops.jl/pull/18
- [ ] Benchmark the simple example to see things slow down. I don't expect to see much of a difference.
- [ ] Refactor the operators and time stepping loop to use the new abstractions!
- [ ] Add tests to make sure any structure that may be passed to a CUDA kernel `isbitstype`. Just construct a bunch of grids, fields, and forcing functions and test that they are indeed `isbitstype`.
- [ ] Benchmark the model with `isbitstype` abstractions to make sure performance hasn't degraded.

**Comment by ali-ramadhan** [comment]
Hit a slight roadblock as the `Field` structs are not `isbitstype`:
```julia
struct CellField{A<:AbstractArray,G<:Grid} <: Field
    data::A
    grid::G
end
```
since `Array`s and `CuArray`s are not `isbits`.

However, @vchuravy points out that a `CuArray` is not `isbits` only because it contains a `finalize` function (essentially a destructor) which makes it not `isbits` on the host. Apparently CUDAnative converts the `CuArray` to some sort of `CuDeviceArray` using [Adapt.jl](https://github.com/JuliaGPU/Adapt.jl) which is `isbits` and can be used as a device argument.

So we'll have to figure out how to _adapt_ our `Field` structs to be `isbits` on the GPU device using Adapt.jl. It shouldn't be too hard as the struct is simple.

I should also check out the `cudaconvert(args...)` function in CUDAnative.

**Comment by glwagner** [comment]
Oh no!

We can still use the `Grid` structs though, right?

**Comment by ali-ramadhan** [comment]
Well, road block might not be the right word as I'm sure we can figure it out. So we can already use the `Grid` struct but would be nice to also be able to use the `Field` struct too. But yeah, using the `Grid` struct would clean up most of the clutter.
