### ISSUE TITLE
Iterate over a node list instead of using nested loops.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#61]
@peterahrens suggested iterating over a list of nodes, e.g. using a `CartesianIndices` iterator instead of looping over all the indices with a nested for loop.

However, according to @vchuravy this may not work with GPUifyLoops.jl right now so this issue has no associated milestone. Actually, see: https://github.com/vchuravy/GPUifyLoops.jl/pull/18#issuecomment-465144732

This will actually be really great once we move to other non-Cartesian grids as we can just use a different iterator (`CubedSphereIndices`?) and not have to modify the time stepping code.

See: [Multidimensional algorithms and iteration](https://julialang.org/blog/2016/02/iteration)

**Comment by glwagner** [comment]
See

https://github.com/glwagner/StencilLab.jl/blob/ca1e9b2f0b32a48cfcd777d1519f7faa1ed14d02/src/kernels.jl#L19

for one way to use a `CartesianIndex`.

**Comment by ali-ramadhan** [comment]
I think we'll end up doing this when we switch to KernelAbstractions.jl anyways so I'm closing this issue as it has become stale.
