### ISSUE TITLE
Make Julia 1.3 the new minimum required version?

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#625]
With Julia 1.3 comes Julia library (JLL) packages which packages are starting to depend on, such as FFTW.jl v1.2.0.

See this blog post for more info: https://julialang.org/blog/2019/11/artifacts/

But this requires Julia 1.3 so as of right now I've pegged Oceananigans.jl to FFTW.jl v1.1.0, an older version to keep Oceananigans.jl compatible with Julia 1.1+ as our README and docs state.

Should we embrace Julia 1.3 so we can keep up to date with all the latest packages?

Note: We already do not support the latest long term support (LTS) release v1.0.5 so we might as well upgrade our requirements to the latest stable release (v.1.3+).

**Comment by vchuravy** [comment]
KernelAbstractions will require 1.3 FYI

**Comment by glwagner** [comment]
I don't mind staying on the bleeding edge here.
