### ISSUE TITLE
More general CUDA thread block layout.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#64]
Right now I'm just constructing grids with dimensions that are multiples of 16 so
```julia
Tx, Ty = 16, 16  # Threads per block
Bx, By, Bz = Int(Nx/Tx), Int(Ny/Ty), Nz  # Blocks in grid.
```

@vchuravy suggested laying them out to fill out the _x_-direction first, then the _y_-direction, then the _z_-direction. That would also let us use grids with arbitrary sizes, i.e. not just multiples of 16. Not sure if it would affect performance for large problems.

See https://github.com/vchuravy/GPUifyLoops.jl/pull/18#issuecomment-465150581

Update: Yeah I should have done this a long time ago. This issue is preventing us from running small grids (e.g. 1D column models) on the GPU and running certain tests.

**Comment by ali-ramadhan** [comment]
I tried to use a more general thread block layout as part of PR #147 but noticed that we have to be pretty careful to not introduce more bugs like #150.

For doing things over the entire 3D grid we need that
```
Tx*Ty*Tz*Bx*By*Bz == Nx*Ny*Nz
```
but for applying boundary conditions in the _z_-direction for example, we need that
```
Tx*Ty*Tz*Bx*By == Nx*Ny
```
so that we can launch `z_apply_bcs!` with `threads=(Tx, Ty, Tz), blocks=(Bx, By)`.

We can fix this by just using different thread block layouts for applying boundary conditions.

Might be good to have a `ThreadBlockLayout` struct.

**Comment by glwagner** [comment]
Could make the 'layout' a property of `GPU`, somehow. Seems like details of parallelization do belong to the `Architecture`.

**Comment by ali-ramadhan** [comment]
Yeah that makes sense. I think we should be able to change the layout or just have different layouts for different purposes (time stepping layout, _z_ boundary conditions layout, etc.).

**Comment by ali-ramadhan** [comment]
Small update: The thread block layout does belong to the GPU architecture but we'll have to store multiple thread-block layouts (one for 3D stuff, one for _x_-boundary conditions, another for _z_-boundary conditions, one for vertical integrals, etc.).

We might be able to come with just four: 3D stuff, _xy_ stuff, _xz_ stuff, and _yz_ stuff. But there may be a reason for using different layouts for _z_-boundary conditions and vertical integrals (right now they would use the same layout).

Then if we do distributed architectures we can store other parallelization parameters, e.g. MPI stuff, under the appropriate `Architecture` struct.

**Comment by ali-ramadhan** [comment]
Just a note that @vchuravy's thread-block layout
```julia
const max_threads = 1024
Tx  = min(max_threads, Nx)
Ty  = min(fld(max_threads, Tx), Ny)
Tz  = min(fld(max_threads, (Tx*Ty)), Nz)
Bx, By, Bz = cld(Nx, Tx), cld(Ny, Ty), cld(Nz, Tz)  # Blocks in grid.
```
is great for nice even sizes, e.g. 256x128x64, but not for weird sizes, e.g. 256x135x71 because then `Tx*Ty*Tz*Bx*By*Bz = 2471936` but `Nx*Ny*Nz = 2453760`.

Might be good to have something that works for all grid sizes (hopefully this is possible), or to spit out an error if `Tx*Ty*Tz*Bx*By*Bz != Nx*Ny*Nz` because otherwise all the time-stepping will be very wrong.

**Comment by ali-ramadhan** [comment]
Closing this issue as @maleadt has figured out how to compute dynamic launch configurations for kernels. @glwagner has also proposed a thread-block layout abstraction in PR #249 that we can switch to if needed.
