### ISSUE TITLE
Integrate opening and closing of Netcdf outputwriters in simulation loop

### ISSUE THREAD

**Issue by suyashbire1** [climate-machine/Oceananigans.jl#650]

**Comment by glwagner** [comment]
Can this issue be clarified? The `JLD2OutputWriter` (and also the `Checkpointer`) is only open during output writing and is otherwise closed; therefore there is no need for `Simulation` to manage anything. Is this issue specific to the `NetCDFOutputWriter`?

**Comment by suyashbire1** [comment]
Yes, sorry. It only pertains to the netcdf outputwriter. Currently, we need the users to write `close(outputwriter)` at the end of their scripts to close open netcdf files. I am hoping to integrate that with `run_simulation`.
