### ISSUE TITLE
Bounded not defined

### ISSUE THREAD

**Issue by truedichotomy** [climate-machine/Oceananigans.jl#679]
I tried running the first example listed in README and I got the following error:
```
julia> topology = (Periodic, Periodic, Bounded)
ERROR: UndefVarError: Bounded not defined
Stacktrace:
 [1] top-level scope at REPL[45]:1
```
I'm running Julia 1.4 RC2 on macOS 10.15.3.

**Comment by glwagner** [comment]
Thanks @truedichotomy ! What version of `Oceananigans` are you using (eg, can you post output from `using Pkg; Pkg.status()`)?

**Comment by glwagner** [comment]
I installed 1.4-rc2, but couldn't reproduce the issue with Oceananigans `v0.25.0`:

```julia
(@v1.4) pkg> st
Status `~/.julia/environments/v1.4/Project.toml`
  [9e8cae18] Oceananigans v0.25.0
```

Nevertheless we should not specify `topology` for that first example, which should be trivial. Try this instead:

```julia
using Oceananigans
grid = RegularCartesianGrid(size=(100, 100, 50), length=(2000, 2000, 1000))
model = IncompressibleModel(grid=grid)
simulation = Simulation(model, Δt=60, stop_time=3600)
run!(simulation)
```

**Comment by glwagner** [comment]
`README` will be updated by #681

**Comment by truedichotomy** [comment]
Thanks! Strange that I'm stuck on v0.18.1 which would likely explain the error. But when I tried to update it, it won't upgrade to 0.25...almost seems like a dependency issue.

**Comment by ali-ramadhan** [comment]
Thanks for opening this issue @truedichotomy!

Oh that's interesting... Do you still have the error you got when trying to update Oceananigans?

Might be good for us to add some information to the README or documentation about how to check the current version and how to update to the latest version (mentioning your error could help other users).

**Comment by truedichotomy** [comment]
I found the issue. Apparently, DiffEqGPU.jl prevents me from updating a bunch of packages. Once, I removed it, Oceananigans is able to upgrade to 0.25.0 and now everything works as expected!

**Comment by ali-ramadhan** [comment]
Ah that makes sense, thank you for investigating!

I think Oceananigans.jl depends on the latest CUDA packages (CUDAnative.jl, CUDAdrv.jl, CuArrays.jl, etc.) while other packages might require older versions of them.

PS: Apologies in advance if parts of the documentation has gone out of date as we've made a lot of improvements recently. But please open another issue if you hit any problems!

**Comment by truedichotomy** [comment]
No problem, thanks for the rapid response!
