### ISSUE TITLE
Includes at the module level cannot have circular dependencies.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#69]
We must play this annoying game of organizing the definitions to avoid mutually circular type declarations.

See: https://github.com/JuliaLang/julia/issues/269

**Comment by ali-ramadhan** [comment]
Closing as we can't do anything about this.

**Comment by astrobc1** [comment]
This should absolutely be addressed.

"We can't do anything about this" is an irresponsible and silly claim to make. Who is "we"? With Julia, you can effectively implement nearly anything you want via macros. Want to do implement (possibly nearly) effective (insert language here) like syntax in Julia? Macros.

Ultimately, this is something to be addressed in the fundamental usage of local namespaces in the base julia language.

I love Julia. But this needs addressed. You can't say "Talks like Python" without such a fundamental Pythonic trait. I've yet to find any reasonable workaround for this. It's not to say there isn't one.

**Comment by ali-ramadhan** [comment]
Hi @astrobc1, this is an ancient issue for the Oceananigans.jl package. We've organized the modules in Oceananigans.jl in a more logical way a long time ago so this issue has not been relevant for over a year.

We (the Oceananigans.jl developers) are not Julia developers and cannot fix https://github.com/JuliaLang/julia/issues/269. If you are interested, it seems that https://github.com/JuliaLang/julia/pull/32658 might resolve the issue as part of Julia 1.6.
