### ISSUE TITLE
Ideas for abstractions.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#70]
https://github.com/JuliaDiffEq/DifferentialEquations.jl

https://github.com/simpeg/discretize

**Comment by glwagner** [comment]
A couple random ideas:

Some things with [FieldVector](http://juliaarrays.github.io/StaticArrays.jl/stable/pages/api.html#FieldVector-1)

```julia
struct Velocities{Tu<:Field,Tv<:Field,Tw<:Field} <: FieldVector{3, Field}
  u::Tu
  v::Tv
  w::Tw
end

U = Velocities(grid)
G_U = Velocities(grid)
G₋₁_U = Velocities(grid)

function define_tracers(names...)
  fieldexprs = [ :( $name::Tc; ) for name in names ]
  :(struct Tracers{Tc} <: FieldVector{$(length(names)), CellField}; $(fieldexprs...); end )
end

eval(define_tracers(:T, :S, :carbon))
c = Tracers(...)
m = Model(..., tracers=c)
```

Probably the `define_tracers` function could be improved, or made into a macro somehow with syntax `c = @tracers :T :S :carbon`... not sure.

**Comment by ali-ramadhan** [comment]
Closing as this is not an actionable issue.
