### ISSUE TITLE
`progress(simulation)` is not always called during `run!`

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#723]
This line:

https://github.com/climate-machine/Oceananigans.jl/blob/6502f078c8f7698a2fb6cd398d9e96cfacccc787/src/Simulations.jl#L166

prevents the method `progress(simulation)` from being called if `progress` is not a subtype of the abstract type `Function`. 

This makes using callable objects for `progress` more complicated (at least, these callable objects would have to subtype `Function`, which seems like an arbitrary requirement for such objects).

What is the reasoning behind requiring `progress` to subtype `Function` (and furthermore enforcing this with an if-statement)? If `progress` does not subtype function, the keyword argument is unused (despite the desperate efforts of flailing users, such as myself).

Callable objects are nice for `progress`. For example, a callable object is a good way to keep track of wall time, make plots, automatically format strings containing diagnostics information, or otherwise reference objects outside `simulation` for the purposes of logging.

**Comment by ali-ramadhan** [comment]
Isn't this a duplicate of #642?

I agree that callable objects should work. I think the solution we discussed in #642 should work:

```julia
iscallable(sim.progress) && sim.progress(sim) 
```

**Comment by glwagner** [comment]
Yep, dup of #642 (more or less)
