### ISSUE TITLE
Possible to have CPU-specific Project/Manifest and a GPU-specific one?

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#79]
Low priority item. But no need to install CUDA packages if you're only going to run on a CPU.

**Comment by vchuravy** [comment]
Either using requires it you can have an app manifest (see test/gpuenv in GPUifyLoops)

**Comment by ali-ramadhan** [comment]
Ah having two app manifests (test/gpuenv and test/cpuenv) looks like a really clean way of doing this, thanks!

**Comment by ali-ramadhan** [comment]
Closing this issue because we do have separate environments, we just don't really use them as you have to specify them manually which is great for CI and testing, but not so great for new users without a GPU...
