### ISSUE TITLE
Appveyor CI is SO slow.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#89]
Each Appveyor build takes 30-50 minutes to run (and they run sequentially) so Appveyor takes forever to finish testing. Compare with ~10 minutes per build on Travis and JuliaGPU's CI on GitLab.

It also builds CUDA packages unsuccessfully so maybe defining a CPU testing env and using it on Travis and Appveyor can help? See https://github.com/ali-ramadhan/Oceananigans.jl/issues/79

Problem might go away on its own but otherwise this might help: https://www.appveyor.com/docs/build-cache/

**Comment by glwagner** [comment]
Should we profile the tests and remove some of them?

**Comment by ali-ramadhan** [comment]
I don't think it's the tests that are slow. One of the tests involves time stepping a model for 10 time steps and it prints the wall clock time taken for each time step. It's only 2-3 ms so it's executing the tests at the expected speed.

I've looked into the logs and it seems to be busy building packages. It's no different than what Travis and GitLab CI do, so maybe this just takes much longer on Windows CI? If we reduce the number of build dependencies that should help then. And if we can cache the builds then that would be excellent.

**Comment by charleskawczynski** [comment]
I've noticed that Travis has been quite slow in the afternoons, I think it may just be traffic related :[

**Comment by ali-ramadhan** [comment]
Ah interesting, that could be it especially since we're using free-tier CI testing.

Looking to see what the final version of https://github.com/climate-machine/CLIMA/issues/106 and https://github.com/climate-machine/CLIMA/issues/107 look like, then would be good to at least use a CPU-only configuration on Appveyor.

**Comment by ali-ramadhan** [comment]
I'm only running the x64 builds so this should reduce Appveyor build times by a half to ~1 hour.

Closing this issue as there's not much else we can do except remove dependencies or pay for better resources. Build cache could help but we'd have to manually update it each time package versions change, etc. and the extra maintenance isn't worth it.
