### ISSUE TITLE
Standard field names for NetCDF output.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#91]
Might be good to choose some standard names for the NetCDF variables (and output in general). Following the standard CMIP6 names might be one idea. Apparently some programs assume that NetCDF variables follow these conventions.

See:
* https://www.earthsystemcog.org/projects/wip/CMIP6DataRequest
* http://clipc-services.ceda.ac.uk/dreq/index/standardname.html

**Comment by glwagner** [comment]
I propose we develop output tools that permit the specification of completely arbitrary output with flexible naming. Then, we can write additional convenience functions that allow users to opt for default/standard output with standardized names.

**Comment by ali-ramadhan** [comment]
Yeah that would be better than hard coding things in.

If we have flexible naming, then we should be able to output data that matches CliMA.jl or data that matches MITgcm output.

**Comment by glwagner** [comment]
I think we want to have users specify output with a function. 

The output type should be a parameter of the output writer. 

When the output type is a field, we can dispatch to a function that will write the grid associated with that field. 

I started working on this on my fork, but realized it is relatively important and not a small job. It also depends on the field abstraction system, which needs some development.

**Comment by ali-ramadhan** [comment]
We have suitable defaults now: https://github.com/climate-machine/Oceananigans.jl/blob/74cfb85fd210e70313f19e9374dd4b9f119f2199/src/OutputWriters/netcdf_output_writer.jl#L90-L97

Closing this issue as long descriptive CMIP6 names like `sea_water_conservative_temperature` may not be the most suitable defaults for Oceananigans.

But indeed `NetCDFOutputWriter` is flexible enough that you can use these names if you wish.
