### ISSUE TITLE
Closure-specific temporary variables.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#94]
> As discussed with @jm-c, I think another feature we will need is the ability to design closure-specific temporary variables.
> 
> For example, the implementation of Constant Smagorinsky or Anisotropic Minimum Dissipation will benefit from the ability to compute the eddy viscosity (at 4 locations in a cell --- 3 `FaceField`s and 1 `CellField`) and re-use it in calculating the contribution of the subgrid closure to the momentum 'source terms'.
> 
> _Originally posted by @glwagner in https://github.com/ali-ramadhan/Oceananigans.jl/issues/73#issuecomment-467660286_

**Comment by ali-ramadhan** [comment]
I think we might be able to get away with recomputing so closing this issue. Also not an actionable issue.

**Comment by johncmarshall54** [comment]
Putting in div.v/delta t in the pressure solve is an urgent priority, as it
a test for the poisson solve.

**Comment by ali-ramadhan** [comment]
@johncmarshall54 Agreed. Working on it as part of issue #161.
